import {Wash2Detail} from '../wash2/Wash2Detail';
import {SMC,Wash1Detail} from './Wash1Detail';
import {useEffect,useState,type Dispatch,type CSSProperties} from 'react';
import type {CheckpointRun,CheckpointAction} from '../checkpoint/research';
import type {CandidateT1State,Wash1State} from './model';
import {wash1Count} from './model';
import {wash1Events} from './fixtures';
import {CandidateDetail} from '../discovery/DiscoveryExperience';
import './wash1.css';
function Trajectory({r}:{r:CandidateT1State}){return <svg className="trajectory" viewBox="0 0 180 100" role="img" aria-label={`${r.ticker} OPS ${r.t0.ops} to ${r.t1.ops}; RAP ${r.t0.rap} to ${r.t1.rap}`}><path className="trajectory-axes" d="M20 5V80H170"/><text x="2" y="12">RAP</text><text x="145" y="96">OPS</text><path className="movement-line" d={`M${20+r.t0.ops*1.4} ${80-r.t0.rap*.7}L${20+r.t1.ops*1.4} ${80-r.t1.rap*.7}`}/><circle className="point-t0" cx={20+r.t0.ops*1.4} cy={80-r.t0.rap*.7} r="3"/><circle className="point-t1" style={{'--dx':`${(r.t0.ops-r.t1.ops)*1.4}px`,'--dy':`${(r.t1.rap-r.t0.rap)*.7}px`} as CSSProperties} cx={20+r.t1.ops*1.4} cy={80-r.t1.rap*.7} r="4"/><text x={20+r.t0.ops*1.4-16} y={80-r.t0.rap*.7+(r.t1.rap<r.t0.rap?-8:13)}>T0</text><text x={20+r.t1.ops*1.4+7} y={80-r.t1.rap*.7+(r.t1.rap<r.t0.rap?13:-5)}>T1</text></svg>}
function Insights({w}:{w:Wash1State}){const all=Object.values(w.results);const groups=[['Underrecognized / investigate',all.filter(r=>r.gap==='LARGE POSITIVE GAP'||r.gap==='POSITIVE GAP'),'Economic evidence is stronger than recognition; timing remains unresolved.'],['Recognition emerging',all.filter(r=>r.gap==='CLOSING POSITIVE GAP'),'Participation is moving toward economic strength, with conversion risks still visible.'],['Market ahead of economics',all.filter(r=>r.gap==='NEGATIVE GAP'),'Participation and expectations outrun the economic evidence established here.']] as const;return <section className="wash-insights" aria-label="Wash 1 insights">{groups.filter(([,r])=>r.length).map(([title,rows,text])=><div key={title}><span className="overline">{title}</span><p>{rows.map(r=>r.ticker).join(', ')} · {text}</p></div>)}</section>}
export function Wash1Experience({run,dispatch}:{run:CheckpointRun;dispatch:Dispatch<CheckpointAction>}){
 const w=run.wash1!;const complete=w.status==='COMPLETE';const [selected,setSelected]=useState(w.participants[0]);const [hover,setHover]=useState<string|null>(null);const [detail,setDetail]=useState<string|null>(null);
 function finish(){for(let index=w.cursor;index<wash1Events.length;index++)dispatch({type:'WASH1_EVENT',index})}
 useEffect(()=>{if(complete)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){finish();return}const timer=window.setTimeout(()=>dispatch({type:'WASH1_EVENT',index:w.cursor}),240);return()=>clearTimeout(timer)},[w.cursor,complete,dispatch]);
 const rows=Object.values(w.results),active=w.results[hover??selected],r=w.results[selected];const activity=run.activity.filter(e=>e.id.startsWith('wash1-'));
 return <section className="wash-one" aria-label="Wash 1 research canvas">
 <p className="wash-note">Discovery state saved locally · {run.runId} · {w.participants.length} candidates entered Wash 1</p>
 <span className="overline">{complete?'Wash 1 complete · T1':'Wash 1'} · local demonstration</span><h2>Reality & Recognition</h2><p className="wash-question">What is actually happening — and what does the market appear to believe?</p>
 <section className={`activity-stream ${complete?'complete':''}`} aria-label="Wash 1 activity"><p role="status">{activity.at(-1)?.message??'Preparing independent analytical states'}</p>{!complete&&<button className="finish-discovery" onClick={finish}>Show complete Wash 1 demonstration</button>}<details><summary>{activity.length} Wash 1 activity events · review history</summary><ol>{activity.map(e=><li key={e.id}>{e.message}</li>)}</ol></details></section>
 <div className="independent-states"><span>Economic Reality <b>{w.economicFrozen?'Frozen':'Establishing'}</b></span><span>Market / Security <b>{w.marketFrozen?'Frozen':w.economicFrozen?'Establishing':'Pending independent review'}</b></span><span>Comparison <b>{w.comparisonComplete?'Complete':'After both states freeze'}</b></span></div>
 {complete&&<><div className="wash-synthesis"><h3>Same thesis. Different analytical states.</h3><p>{rows.filter(r=>r.gap.includes('POSITIVE')).length} of {rows.length} candidates show economics ahead of recognition; {rows.filter(r=>r.gap==='NEGATIVE GAP').length} show market behavior ahead of economics. {rows.filter(r=>r.disposition!=='ADVANCE').length} remain on HOLD or REVIEW. No single score resolves these tensions.</p></div>
 <section aria-label="Economic Reality × Market Recognition map" className="reality-map-section"><h3>Economic Reality × Market Recognition</h3><p className="wash-note">Illustrative relative positions, not calibrated measurements. Select a candidate to inspect the independent states.</p><div className="reality-map"><span className="axis-y">Economic Reality · stronger ↑</span><span className="axis-x">Market Recognition · stronger →</span><span className="map-region">Economics ahead · investigate</span>{rows.map(c=><button key={c.ticker} style={{left:`${8+c.map.recognition*.82}%`,bottom:`${10+c.map.reality*.78}%`}} className={`${selected===c.ticker?'selected':''} ${w.excluded.includes(c.ticker)?'user-excluded':''}`} aria-pressed={selected===c.ticker} aria-label={`Select ${c.ticker} reality and recognition`} onMouseEnter={()=>setHover(c.ticker)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(null)} onClick={()=>setSelected(c.ticker)}>{c.ticker}</button>)}</div><div className="map-reading" aria-live="polite">{active&&<><b>{active.ticker} · {active.gap}</b><div className="independent-states"><div>Economic Reality<SMC value={active.economic}/></div><div>Market Recognition<SMC value={active.recognition}/></div></div><p>{active.gapExplanation}</p></>}</div><details className="wash-help"><summary>How to read the discrepancy</summary><p>Economic Reality is informed by Fundamental Quality and Business Demand. Market Recognition considers Security Demand, embedded Expectations and Technical Regime without merging their specialist states.</p><p>Favorable economics with weak price response is an investigative discrepancy, not proof of mispricing. A closing positive gap is a potential repricing state, not an automatic investment signal.</p></details></section>
 <section aria-label="T0 to T1 trajectories"><h3>What changed from T0 to T1?</h3><p className="wash-note">OPS · Opportunity Potential Score. RAP · Risk Adjusted Potential. Illustrative research-navigation coordinates, not price targets, return forecasts, profit probabilities or trade recommendations.</p><div className="trajectory-grid">{rows.map(c=><button key={c.ticker} aria-label={`Select ${c.ticker} trajectory`} aria-pressed={selected===c.ticker} className={selected===c.ticker?'selected':''} onClick={()=>setSelected(c.ticker)}><b>{c.ticker}</b><Trajectory r={c}/><span>OPS {c.t0.ops} → {c.t1.ops} · RAP {c.t0.rap} → {c.t1.rap}</span></button>)}</div>{r&&<div className="movement-explanation"><span className="overline">{r.ticker} · Why did it move?</span><p>{r.t1.why}</p></div>}</section>
 <Insights w={w}/>
 {r&&<section className="wash-inspection" aria-label="Selected Wash 1 candidate"><span className="overline">{r.ticker} · inspect the tension</span><h3>{r.gap}</h3>{r.contradictions.map(t=><p key={t}>{t}</p>)}<button className="wash-inspect-button" onClick={()=>setDetail(selected)}>Inspect {r.ticker} · Discovery + Wash 1</button><p className="wash-note">{w.discovery[r.ticker].candidate.recall?'Entered through Discovery Recall. ':''}Prepared illustrative findings; no current company research. Confidence is uncertainty, not a hidden State penalty.</p></section>}
 <section className="wash-curation" aria-label="Wash 1 candidate curation"><h3>Carry the evidence forward</h3><p className="wash-note">ADVANCE candidates may proceed. REVIEW and HOLD remain inspectable. Your exclusions are separate decisions; T0 and T1 are retained.</p>{rows.map(c=><div key={c.ticker} className={`wash-candidate ${selected===c.ticker?'selected':''}`}><button aria-label={`Select ${c.ticker} Wash 1 summary`} onClick={()=>setSelected(c.ticker)}><b>{c.ticker}{w.discovery[c.ticker].candidate.recall&&<small>Discovery Recall</small>}</b><span>{c.economic.state} economics · {c.recognition.state} recognition<small>{c.gap}</small><small>{c.cycle.from} → {c.cycle.to} · {c.regime}</small></span><span>T1 · {c.t1.ops} OPS / {c.t1.rap} RAP<small>{c.disposition}{w.excluded.includes(c.ticker)?' · USER EXCLUDED':''}</small></span></button>{!run.wash2&&<button className="curation-control" onClick={()=>dispatch({type:'CURATE_WASH1',ticker:c.ticker})} aria-label={`${w.excluded.includes(c.ticker)?'Re-include':'Exclude'} ${c.ticker} from Wash 1`}>{w.excluded.includes(c.ticker)?'Re-include':'Exclude'}</button>}</div>)}<details><summary>Wash 1 decision history · {w.decisions.length}</summary>{w.decisions.map(d=><p key={d.ordinal}>{d.ticker} · {d.decision}</p>)}</details></section>
 {!run.wash2&&<div className="discovery-proceed"><span>{wash1Count(w)} candidates eligible for Wash 2</span><button disabled={!wash1Count(w)} onClick={()=>dispatch({type:'START_WASH2'})}>Proceed to Wash 2 →</button>{w.readyForWash2&&<p role="status">Wash 1 state ready. Wash 2 begins in the next approved checkpoint. Local state only.</p>}</div>}
 </>}
 {detail&&w.results[detail]&&<CandidateDetail entry={w.discovery[detail]} discovery={run.discovery!} close={()=>setDetail(null)} compactHistory={!!run.wash2?.results[detail]}>{run.wash2?.results[detail]?<><details><summary>Wash 1 · Reality & Recognition</summary><Wash1Detail r={w.results[detail]}/></details><Wash2Detail r={run.wash2.results[detail]}/></>:<Wash1Detail r={w.results[detail]}/>}</CandidateDetail>}
 </section>
}
