import {useEffect,useState,type CSSProperties,type Dispatch} from 'react';
import type {CheckpointRun,CheckpointAction} from '../checkpoint/research';
import type {CandidateT2State} from './model';
import {wash2Count} from './model';
import {wash2Events} from './fixtures';
import {CandidateDetail} from '../discovery/DiscoveryExperience';
import {Wash1Detail,SMC} from '../wash1/Wash1Detail';
import {Wash2Detail} from './Wash2Detail';
import './wash2.css';
function CausalChain({r}:{r:CandidateT2State}){
 const [selected,setSelected]=useState<number|null>(null);const [hover,setHover]=useState<number|null>(null);const l=r.chain[hover??selected??0];const chosen=selected===null?null:r.chain[selected];
 return <section className="causal-chain" aria-label="Causal transmission"><h3>How does the thesis become {r.ticker}’s economics?</h3><p className="wash-note">Causal exposure requires transmission into orders and cash. Narrative association alone is insufficient.</p><div className="causal-links">{r.chain.map((link,i)=><button key={i} className={`causal-link ${link.state==='Fragile'||link.state==='Unresolved'?'weak-link':''}`} aria-label={`Inspect ${r.ticker} causal link ${i+1}: ${link.from} to ${link.to}`} aria-pressed={selected===i} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(i)} onBlur={()=>setHover(null)} onClick={()=>{setSelected(i);setHover(null)}}><span>{String(i+1).padStart(2,'0')}</span><b>{link.from}<small>↓</small>{link.to}</b><span>{link.state}<small>{link.confidence} confidence</small></span></button>)}</div><div className="causal-interpretation" aria-live="polite"><b>{l.from} → {l.to}</b><p>{l.reason}</p>{chosen&&<dl><dt>Selected link</dt><dd>{chosen.from} → {chosen.to}</dd><dt>Evidence · illustrative</dt><dd>{chosen.evidence}</dd><dt>Principal weakness</dt><dd>{chosen.weakness}</dd><dt>Timing / lag</dt><dd>{chosen.lag}</dd></dl>}<small>{selected===null?'Select a link to inspect evidence, weaknesses and timing.':'Selected link · '+chosen?.state+' · '+chosen?.confidence+' confidence'}</small></div></section>
}
export function Wash2Experience({run,dispatch}:{run:CheckpointRun;dispatch:Dispatch<CheckpointAction>}){
 const w=run.wash2!;const complete=w.status==='COMPLETE';const [selected,select]=useState(w.participants[0]);const [detail,setDetail]=useState<string|null>(null);const r=w.results[selected];const rows=Object.values(w.results);
 function finish(){for(let index=w.cursor;index<wash2Events.length;index++)dispatch({type:'WASH2_EVENT',index})}
 useEffect(()=>{if(complete)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){finish();return}const timer=window.setTimeout(()=>dispatch({type:'WASH2_EVENT',index:w.cursor}),240);return()=>clearTimeout(timer)},[w.cursor,complete,dispatch]);
 const activity=run.activity.filter(e=>e.id.startsWith('wash2-'));
 const dependencies=[...new Set(rows.flatMap(c=>c.context.dependencies))].map(name=>({name,candidates:rows.filter(c=>c.context.dependencies.includes(name))}));
 const shared=dependencies.filter(d=>d.candidates.length>1);
 return <section className="wash-two wash-one" aria-label="Wash 2 research canvas"><p className="wash-note">Wash 1 state saved locally · {run.runId} · {w.participants.length} candidates entered Wash 2</p><span className="overline">{complete?'Wash 2 complete · T2':'Wash 2'} · local demonstration</span><h2>Thesis Survival</h2><p className="wash-question">Even if what we are seeing is real, should it continue?</p><section className={`activity-stream ${complete?'complete':''}`} aria-label="Wash 2 activity"><p role="status">{activity.at(-1)?.message??'Preparing the curated Wash 1 state'}</p>{!complete&&<button className="finish-discovery" onClick={finish}>Show complete Wash 2 demonstration</button>}<details><summary>{activity.length} Wash 2 activity events · review history</summary><ol>{activity.map(e=><li key={e.id}>{e.message}</li>)}</ol></details></section>
 {complete&&r&&<><section className="survival-synthesis" aria-label="Thesis Survival synthesis"><h3>Opportunity is not the same as durability.</h3><div className="survival-counts">{[...new Set(rows.map(c=>c.survival))].map(s=><span key={s}><b>{rows.filter(c=>c.survival===s).length}</b>{s}</span>)}</div><p>{rows.filter(c=>c.disposition==='ADVANCE').length} of {rows.length} are eligible to advance. Conditions and challenges remain visible; these are qualitative demonstration states, not success probabilities.</p></section>
 <section className="survival-comparison" aria-label="Thesis Survival comparison"><h3>Transmission versus fragility</h3><p className="wash-note">Compare whether a credible causal path can withstand its principal constraint.</p><div className="comparison-labels" aria-hidden="true"><span>Candidate</span><span>Causal strength</span><span>Principal fragility</span></div>{rows.map(c=><button key={c.ticker} aria-label={`Select ${c.ticker} survival`} aria-pressed={selected===c.ticker} onClick={()=>select(c.ticker)}><b>{c.ticker}<small>{c.survival}</small></b><span>{c.ct.state}<small>{c.ct.momentum} · {c.ct.confidence} confidence</small></span><span>{c.fragilities[0].mechanism}<small>{c.fragilities[0].severity}</small></span></button>)}</section>
 <CausalChain key={selected} r={r}/>
 <section className="fragility-surface" aria-label="Material fragilities"><span className="overline">{r.ticker} · RF-01</span><h3>Where does the thesis become fragile?</h3>{r.fragilities.map(f=><div key={f.mechanism}><h4>{f.mechanism}</h4><p>{f.effect}</p><dl className="fragility-dimensions">{[['Likelihood context',f.likelihood],['Severity',f.severity],['Horizon',f.horizon],['Mitigability',f.mitigability],['Confidence',f.confidence]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>)}<div className="failure-surface"><h4>What breaks this thesis?</h4>{r.failureConditions.map(f=><p key={f}>{f}</p>)}</div></section>
 <section className="survival-context" aria-label="Thesis Survival context"><h3>Context changes the path, not just the score.</h3><details open><summary>BR-01 · Historical analogue support: {r.br.support}</summary><p>{r.br.analogue}</p><p>{r.br.limitation}</p><details><summary>Similarity, differences & confidence</summary><p>{r.br.similarity}</p><p>{r.br.difference}</p><p>Confidence: {r.br.confidence}</p></details></details><p className="wash-note">CT/RF/BR form the historical minimum. The following MR/SI/DC findings demonstrate broader Thesis-Survival context; they are not claimed as universal historical Wash 2 execution.</p><details><summary>MR-01 · Relevant macro context</summary>{r.context.macro.map(m=><div key={m.factor}><h4>{m.factor} · {m.state}</h4><p>{m.explanation}</p></div>)}<p className="wash-note">Scenario context only; no live macro values and no universal macro veto.</p></details><details><summary>SI-01 · Industry: {r.context.industry.state}</summary><p>{r.context.industry.explanation}</p><p>{r.context.industry.valueAccrual}</p><p className="wash-note">Industry expansion/compression describes commercial conditions. CF measures investor participation; TR measures price/volatility structure.</p></details></section>
 <section className="dependency-surface" aria-label="Shared dependencies"><h3>Different securities. Some of the same causes.</h3><p className="wash-note">DC-01 · Select a candidate within a dependency to follow its complete survival analysis.</p>{dependencies.map(d=><div className="dependency-row" key={d.name}><span>{d.name}<small>{d.candidates.length>1?'Shared exposure':'Candidate-specific exposure in this set'}</small></span><div>{d.candidates.map(c=><button key={c.ticker} aria-label={`Select ${c.ticker} via ${d.name}`} aria-pressed={selected===c.ticker} onClick={()=>select(c.ticker)}>{c.ticker}</button>)}</div></div>)}<p className="shared-risk-insight">{shared.length?`${shared[0].candidates.length} candidates share ${shared[0].name.toLowerCase()}. Diversifying across these securities does not fully diversify that underlying thesis risk.`:'No shared dependency is established within this curated set. A single candidate still carries its own thesis dependencies.'}</p></section>
 <section aria-label="T0 to T2 trajectories"><h3>What did Thesis Survival change?</h3><p className="wash-note">OPS / RAP are illustrative research-navigation coordinates, not calibrated return forecasts. Hollow points retain history; T2 records this stage.</p><div className="trajectory-grid">{rows.map(c=>{const old=w.prior[c.ticker];const points=[old.t0,old.t1,c.t2];return <button key={c.ticker} aria-label={`Select ${c.ticker} T1 to T2 trajectory`} aria-pressed={selected===c.ticker} className={selected===c.ticker?'selected':''} onClick={()=>select(c.ticker)}><b>{c.ticker}</b><svg className="trajectory" viewBox="0 0 180 110" role="img" aria-label={`${c.ticker}: T0 ${old.t0.ops}/${old.t0.rap}, T1 ${old.t1.ops}/${old.t1.rap}, T2 ${c.t2.ops}/${c.t2.rap} OPS/RAP`}><path className="trajectory-axes" d="M15 5V88H170"/><text x="1" y="10">RAP</text><text x="147" y="104">OPS</text><path className="prior-path" d={`M${15+old.t0.ops*1.45} ${88-old.t0.rap*.78}L${15+old.t1.ops*1.45} ${88-old.t1.rap*.78}`}/><path className="movement-line" d={`M${15+old.t1.ops*1.45} ${88-old.t1.rap*.78}L${15+c.t2.ops*1.45} ${88-c.t2.rap*.78}`}/>{points.map((p,i)=><g key={i}><circle className={i===2?'point-t1':'point-t0'} cx={15+p.ops*1.45} cy={88-p.rap*.78} r={i===2?4:3} style={i===2?{'--dx':`${(old.t1.ops-p.ops)*1.45}px`,'--dy':`${(p.rap-old.t1.rap)*.78}px`} as CSSProperties:undefined}/><text x={15+p.ops*1.45+(i===2?7:-13)} y={88-p.rap*.78+(i===0?13:i===1?-8:c.t2.rap<old.t1.rap?13:-5)}>T{i}</text></g>)}</svg><span>T0 {old.t0.ops}/{old.t0.rap} → T1 {old.t1.ops}/{old.t1.rap} → T2 {c.t2.ops}/{c.t2.rap}</span></button>})}</div><div className="movement-explanation"><span className="overline">{r.ticker} · T1 → T2</span><p>{r.t2.why}</p></div></section>
 <section className="wash-insights" aria-label="Wash 2 insights"><div><span className="overline">Causal durability</span><p>{rows.filter(c=>c.ct.state==='Strong').map(c=>c.ticker).join(', ')||'No candidate in this set'}: strong transmission in this fixture, still subject to explicit conditions.</p></div><div><span className="overline">Limited analogue confidence</span><p>Historical-cycle context supplies no calibrated success rate. Company capture and the current demonstration regime remain distinct.</p></div><div><span className="overline">{r.ticker} · preserved contradiction</span>{r.contradictions.map(c=><p key={c}>{c}</p>)}</div></section>
 <section aria-label="Selected Wash 2 candidate"><span className="overline">{r.ticker} · {r.survival}</span><SMC value={r.ct}/><p>{r.reason}</p><button className="wash-inspect-button" onClick={()=>setDetail(selected)}>Inspect {r.ticker} · full research history</button><p className="wash-note">{run.wash1!.discovery[r.ticker].candidate.recall?'Entered through Discovery Recall. ':''}Prepared illustration, not current company research.</p></section>
 <section className="wash-curation" aria-label="Wash 2 candidate curation"><h3>Carry the surviving thesis forward</h3><p className="wash-note">ADVANCE, REVIEW and HOLD are research dispositions. Your exclusions are separate and never remove T0, T1 or T2.</p>{rows.map(c=><div key={c.ticker} className={`wash-candidate ${selected===c.ticker?'selected':''}`}><button aria-label={`Select ${c.ticker} Wash 2 summary`} onClick={()=>select(c.ticker)}><b>{c.ticker}<small>{c.survival}</small></b><span>{c.ct.state} causal strength<small>{c.fragilities[0].mechanism}</small><small>Macro: {c.context.macro[0].state} · Industry: {c.context.industry.state}</small></span><span>T2 · {c.t2.ops} OPS / {c.t2.rap} RAP<small>{c.disposition}{w.excluded.includes(c.ticker)?' · USER EXCLUDED':''}</small></span></button><button className="curation-control" onClick={()=>dispatch({type:'CURATE_WASH2',ticker:c.ticker})} aria-label={`${w.excluded.includes(c.ticker)?'Re-include':'Exclude'} ${c.ticker} from Wash 2`}>{w.excluded.includes(c.ticker)?'Re-include':'Exclude'}</button></div>)}<details><summary>Wash 2 decision history · {w.decisions.length}</summary>{w.decisions.map(d=><p key={d.ordinal}>{d.ticker} · {d.decision}</p>)}</details></section>
 <div className="discovery-proceed"><span>{wash2Count(w)} candidates eligible for Wash 3</span><button disabled={!wash2Count(w)} onClick={()=>dispatch({type:'READY_FOR_WASH3'})}>Proceed to Wash 3 →</button>{w.readyForWash3&&<p role="status">Wash 2 state ready. Wash 3 begins in the next approved checkpoint. Local state only.</p>}</div>
 </>}
 {detail&&w.results[detail]&&<CandidateDetail entry={run.wash1!.discovery[detail]} discovery={run.discovery!} close={()=>setDetail(null)} compactHistory><details><summary>Wash 1 · Reality & Recognition</summary><Wash1Detail r={w.prior[detail]}/></details><Wash2Detail r={w.results[detail]}/></CandidateDetail>}
 </section>
}
