import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import App from '../App';
import { initialCheckpoint, checkpointReducer, localAssistant } from '../checkpoint/research';
async function send(text: string) { fireEvent.change(screen.getByRole('textbox'), { target: { value: text } }); fireEvent.click(screen.getByRole('button', { name: /Begin thesis conversation|Send reply/ })); await waitFor(() => expect(screen.getByText(text, { exact: true, selector: '.chat-message p' })).toBeInTheDocument()); }
async function finish() { await send('AI infrastructure requires more power and cooling.'); await send('Benefits not yet visible'); await send('two years'); await send('orders fail to become cash'); }
describe('Checkpoint 1 continuous canvas', () => {
    it('opens with the actual canonical SVG and no progression or dashboard', () => { render(<App />); expect(screen.getByRole('img', { name: 'Fidelis' })).toHaveAttribute('src', expect.stringContaining('fidelis-logo.svg')); expect(screen.getByText('What are you seeing?')).toBeVisible(); expect(screen.queryByRole('navigation')).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Log in' })).toBeDisabled(); expect(document.querySelector('.checkpoint')).toHaveClass('arrival-mode'); });
    it('accumulates messages, develops structure and resolves a coherent thesis', async () => { render(<App />); await send('AI infrastructure requires more power and cooling.'); await send('Benefits not yet visible'); expect(screen.getByText('AI infrastructure requires more power and cooling.', { exact: true })).toBeInTheDocument(); expect(screen.getByText(/testing a lag/)).toBeInTheDocument(); expect(screen.getByText('Thesis taking shape')).toBeInTheDocument(); await send('two years'); await send('orders fail to become cash'); expect(screen.getByRole('region', { name: 'Final thesis' })).toBeInTheDocument(); expect(screen.getByRole('heading', { level: 2 })).toHaveTextContent('two years'); expect(document.querySelectorAll('.chat-message')).toHaveLength(8); });
    it('edits before lock and transforms the same canvas without entering Wash 1', async () => { render(<App />); const logo = screen.getByRole('img', { name: 'Fidelis' }); await finish(); fireEvent.click(screen.getByRole('button', { name: 'Edit thesis' })); fireEvent.change(screen.getByLabelText('Edit your thesis'), { target: { value: 'A carefully revised testable thesis.' } }); fireEvent.click(screen.getByRole('button', { name: 'Save thesis' })); fireEvent.click(screen.getByRole('button', { name: 'Lock & begin research' })); expect(screen.getByRole('img', { name: 'Fidelis' })).toBe(logo); expect(screen.getByText('Thesis locked · FID-DEMO-003')).toBeVisible(); expect(screen.getByRole('navigation')).toBeVisible(); expect(document.querySelector('.progression-rail .completed')).toHaveTextContent('Thesis'); expect(document.querySelector('[aria-current="step"]')).toHaveTextContent('Discovery'); expect(screen.getByRole('region', { name: 'Discovery research canvas' })).toBeVisible(); fireEvent.click(screen.getByRole('button', { name: 'Review completed thesis' })); expect(screen.getByRole('heading', {name:'A carefully revised testable thesis.'})).toBeVisible(); expect(screen.queryByRole('button', { name: 'Edit thesis' })).not.toBeInTheDocument(); expect(document.querySelectorAll('.chat-message')).toHaveLength(8); });
    it('uses a replaceable local adapter with state-dependent responses', async () => { const first = await localAssistant.respond({ message: 'AI infrastructure', thesis: null }); const already = await localAssistant.respond({ message: 'already appearing in results', thesis: first.thesis }); const unseen = await localAssistant.respond({ message: 'not visible yet', thesis: first.thesis }); expect(already.message).not.toBe(unseen.message); expect(already.thesis.observation).toBe('AI infrastructure'); });
    it('freezes the run and emits only the actual local lock event', async () => { let r = initialCheckpoint(); for (const message of ['AI infrastructure', 'not visible', 'two years', 'cash conversion fails']) {
        const response = await localAssistant.respond({ message, thesis: r.drafts.at(-1) ?? null });
        r = checkpointReducer(r, { type: 'REPLY', input: message, response });
    } const locked = checkpointReducer(r, { type: 'LOCK' }); expect(checkpointReducer(locked, { type: 'EDIT', text: 'Changed' })).toBe(locked); expect(locked.activity.map(e => e.type)).toEqual(['THESIS_LOCKED']); expect(locked.universe).toEqual({}); expect(locked.washes).toEqual([]); expect(locked.pending).toBeNull(); });
    it('completes in reduced motion with no network dependency', async () => { const fetch = vi.spyOn(globalThis, 'fetch'); const media = vi.spyOn(window, 'matchMedia').mockReturnValue({ matches: true } as MediaQueryList); render(<App />); await finish(); fireEvent.click(screen.getByRole('button', { name: 'Lock & begin research' })); expect(screen.getByRole('heading', { name: 'Relevance, before merit.' })).toBeVisible(); expect(fetch).not.toHaveBeenCalled(); fetch.mockRestore(); media.mockRestore(); });
});
