import {useReducer} from 'react';
import {render,screen,fireEvent,within,act} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {describe,it,expect,vi,afterEach} from 'vitest';
import {initialCheckpoint,checkpointReducer,localAssistant,type CheckpointRun} from '../checkpoint/research';
import {DiscoveryExperience} from '../discovery/DiscoveryExperience';
import {discoveryEvents} from '../discovery/fixtures';
import {discoveryCounts} from '../discovery/model';
async function locked(){let r=initialCheckpoint();for(const message of ['AI infrastructure','not visible','two years','orders fail to convert']){const response=await localAssistant.respond({message,thesis:r.drafts.at(-1)??null});r=checkpointReducer(r,{type:'REPLY',input:message,response})}return checkpointReducer(r,{type:'LOCK'})}
function complete(r:CheckpointRun){return discoveryEvents.reduce((run,event)=>checkpointReducer(run,{type:'DISCOVERY_EVENT',event}),r)}
function Harness({initial}:{initial:CheckpointRun}){const [run,dispatch]=useReducer(checkpointReducer,initial);return <DiscoveryExperience run={run} dispatch={dispatch}/>}
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks()});
describe('Discovery event state',()=>{
 it('starts only after lock, preserves the thesis, and ignores duplicate/out-of-order events',async()=>{const r=await locked();expect(r.discovery?.status).toBe('RUNNING');expect(checkpointReducer(r,{type:'DISCOVERY_EVENT',event:discoveryEvents[2]})).toBe(r);const next=checkpointReducer(r,{type:'DISCOVERY_EVENT',event:discoveryEvents[0]});expect(next.activity.at(-1)?.type).toBe('DISCOVERY_STARTED');expect(checkpointReducer(next,{type:'DISCOVERY_EVENT',event:discoveryEvents[0]})).toBe(next);expect(next.lockedThesis).toBe(r.lockedThesis)});
 it('reconciles first pass, rejection and recall without fabricating market analysis',async()=>{const run=complete(await locked());expect(discoveryCounts(run.discovery!)).toEqual({examined:9,validated:7,rejected:2,pending:0,recall:1,proceed:7});expect(run.discovery?.candidates.PWR.candidate.recall).toBe(true);expect(run.discovery?.candidates.GLW.validation).toBe('REJECTED');expect(run.washes).toEqual([]);expect(run.stage).toBe('DISCOVERY');expect(run.activity.filter(e=>e.type==='DISCOVERY_COMPLETE')).toHaveLength(1)});
 it('preserves candidate and decision history across exclusion and restoration; proceed never runs a wash',async()=>{let r=complete(await locked());const original=r.discovery!.candidates.VRT.candidate;r=checkpointReducer(r,{type:'CURATE_DISCOVERY',ticker:'VRT'});expect(discoveryCounts(r.discovery!).proceed).toBe(6);expect(r.discovery!.candidates.VRT.userState).toBe('USER_EXCLUDED');expect(r.discovery!.candidates.VRT.candidate).toBe(original);r=checkpointReducer(r,{type:'CURATE_DISCOVERY',ticker:'VRT'});expect(r.discovery!.decisions.map(x=>x.decision)).toEqual(['USER_EXCLUDED','USER_REINCLUDED']);r=checkpointReducer(r,{type:'READY_FOR_WASH'});expect(r.discovery?.readyToSave).toBe(true);expect(r.washes).toEqual([]);expect(r.stage).toBe('DISCOVERY');expect(checkpointReducer(r,{type:'CURATE_DISCOVERY',ticker:'GLW'})).toBe(r)});
});
describe('Discovery canvas',()=>{
 it('renders sequential activity before candidates arrive',async()=>{const r=await locked();vi.useFakeTimers();render(<Harness initial={r}/>);expect(screen.queryByLabelText('Thesis causal map')).not.toBeInTheDocument();act(()=>vi.advanceTimersByTime(380));expect(screen.getByRole('status')).toHaveTextContent('Beginning demonstration Discovery');expect(screen.queryByRole('button',{name:/Inspect NVDA/})).not.toBeInTheDocument();act(()=>vi.advanceTimersByTime(380));expect(screen.getByRole('status')).toHaveTextContent('Mapping thesis causal pathways')});
 it('coordinates map, details and user curation without network calls',async()=>{const fetch=vi.spyOn(globalThis,'fetch');render(<Harness initial={await locked()}/>);fireEvent.click(screen.getByRole('button',{name:'Show complete demonstration'}));const thermal=screen.getByRole('region',{name:'Thermal management'});fireEvent.mouseEnter(within(thermal).getByRole('button',{name:/Inspect VRT/}));expect(thermal).toHaveClass('path-active');fireEvent.click(within(thermal).getByRole('button',{name:/Inspect VRT/}));const detail=screen.getByRole('dialog',{name:'VRT Discovery detail'});expect(within(detail).getByText(/Higher rack density/)).toBeVisible();expect(within(detail).getAllByText('Not yet evaluated')).toHaveLength(2);fireEvent.click(screen.getByRole('button',{name:'Close candidate detail'}));fireEvent.click(screen.getByRole('button',{name:'Exclude VRT'}));expect(screen.getByRole('region',{name:'Excluded by you'})).toHaveTextContent('VRT');expect(screen.getByText('candidates will proceed').querySelector('b')).toHaveTextContent('6');fireEvent.click(screen.getByRole('button',{name:'Re-include VRT'}));expect(screen.getByText('candidates will proceed').querySelector('b')).toHaveTextContent('7');fireEvent.click(screen.getByRole('button',{name:/Proceed to Wash 1/}));expect(screen.queryByRole('button',{name:/Proceed to Wash 1/})).not.toBeInTheDocument();expect(fetch).not.toHaveBeenCalled()});
 it('supports reduced motion, Recall, and keyboard candidate selection',async()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:true} as MediaQueryList);render(<Harness initial={await locked()}/>);expect(screen.getByText(/9 examined · 7 validated/)).toBeVisible();expect(screen.getByRole('button',{name:'Inspect PWR on Electrical infrastructure pathway'})).toBeVisible();const candidate=screen.getByRole('button',{name:'Inspect ANET on Networking pathway'});candidate.focus();await userEvent.keyboard('{Enter}');expect(screen.getByRole('dialog',{name:'ANET Discovery detail'})).toBeVisible()});
});
