import {useReducer} from 'react';
import {describe,it,expect,vi,afterEach} from 'vitest';
import {render,screen,within,fireEvent,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../App';
import {checkpointReducer,initialCheckpoint,localAssistant,type CheckpointRun} from '../checkpoint/research';
import {discoveryEvents} from '../discovery/fixtures';
import {wash1Events} from '../wash1/fixtures';
import {wash2Events} from '../wash2/fixtures';
import {wash3Events} from '../wash3/fixtures';
import {ExpressionExperience} from '../expression/ExpressionExperience';
import {buildExpression,readDemoIntent,familyNames} from '../expression/fixtures';
import {expressionFamilies} from '../expression/model';
async function wash3(){let r=initialCheckpoint();r=checkpointReducer(r,{type:'REPLY',input:'AI infrastructure',response:await localAssistant.respond({message:'AI infrastructure',thesis:null})});r=checkpointReducer(r,{type:'LOCK'});for(const event of discoveryEvents)r=checkpointReducer(r,{type:'DISCOVERY_EVENT',event});r=checkpointReducer(r,{type:'START_WASH1'});for(let index=0;index<wash1Events.length;index++)r=checkpointReducer(r,{type:'WASH1_EVENT',index});r=checkpointReducer(r,{type:'START_WASH2'});for(let index=0;index<wash2Events.length;index++)r=checkpointReducer(r,{type:'WASH2_EVENT',index});r=checkpointReducer(r,{type:'START_WASH3'});for(let index=0;index<wash3Events.length;index++)r=checkpointReducer(r,{type:'WASH3_EVENT',index});return r}
async function entered(){let r=await wash3();for(const ticker of ['ANET','ETN'])r=checkpointReducer(r,{type:'SELECT_FINALIST',ticker});return checkpointReducer(r,{type:'START_EXPRESSION'})}
const reply=(r:CheckpointRun,ticker='ANET',text='Asymmetric upside')=>checkpointReducer(r,{type:'EXPRESSION_REPLY',ticker,text});
function Harness({initial}:{initial:CheckpointRun}){const [run,dispatch]=useReducer(checkpointReducer,initial);return <ExpressionExperience run={run} dispatch={dispatch}/>}
afterEach(()=>vi.restoreAllMocks());
describe('Expression downstream state',()=>{
 it('requires completed Wash 3 and an actual eligible selection',async()=>{expect(checkpointReducer(initialCheckpoint(),{type:'START_EXPRESSION'}).expression).toBeNull();let r=await wash3();expect(checkpointReducer(r,{type:'START_EXPRESSION'})).toBe(r);r=checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'ANET'});const selected=r.finalists;r=checkpointReducer(r,{type:'START_EXPRESSION'});expect(r.expression!.participants).toEqual(['ANET']);expect(r.finalists).toBe(selected);expect(r.stage).toBe('EXPRESSION');expect(checkpointReducer(r,{type:'START_EXPRESSION'})).toBe(r)});
 it('rejects failed, insufficient, excluded or non-selected upstream entries',async()=>{const initial=await wash3();for(const mutation of ['failure','evidence','excluded','unselected']){const r=structuredClone(initial);r.wash3!.selected=['ANET'];r.finalists=[{ticker:'ANET',selected:mutation!=='unselected'}];if(mutation==='failure')r.wash3!.results.ANET.verdict='THESIS FAILURE';if(mutation==='evidence')r.wash3!.results.ANET.integrity.sufficient=false;if(mutation==='excluded')r.universe.ANET.userExcluded=true;expect(checkpointReducer(r,{type:'START_EXPRESSION'})).toBe(r)}});
 it('inherits horizon, timing, expectations, adversarial findings and lineage without rewriting T0–T3',async()=>{const r=await entered();const c=r.expression!.finalists.ETN.context;expect(c.horizon).toBe(r.lockedThesis!.horizon);expect(c.t3).toEqual(r.wash3!.results.ETN);expect(c.t1.ve).toEqual(r.wash1!.results.ETN.ve);expect(c.trajectory).toEqual(r.universe.ETN.trajectory);expect(c.trajectory.map(p=>p.t)).toEqual([0,1,2,3]);expect(c.lineage.prior).toBe('WASH_3_T3');expect(c.lineage.liveData).toBe(false)});
 it('keeps separate drafts, conversations, objectives and confirmations per finalist',async()=>{let r=await entered();r=checkpointReducer(r,{type:'EXPRESSION_DRAFT',ticker:'ETN',text:'My unfinished thought'});r=reply(r);r=checkpointReducer(r,{type:'CONFIRM_EXPRESSION',ticker:'ANET'});const a=r.expression!.finalists.ANET;r=checkpointReducer(r,{type:'SWITCH_EXPRESSION_FINALIST',ticker:'ETN'});expect(r.expression!.finalists.ETN.draft).toBe('My unfinished thought');r=reply(r,'ETN','Defined-risk exposure');expect(r.expression!.finalists.ANET).toBe(a);expect(r.expression!.finalists.ETN.analysis!.objective.intent).toBe('DEFINED_RISK');expect(r.expression!.finalists.ANET.confirmed).toBe('LONG_CALL')});
 it('changes preferences and Expression horizon without mutating any upstream analytical state',async()=>{const initial=await entered();let r=reply(initial,'ANET','Defined-risk exposure; horizon: 18 months');r=checkpointReducer(r,{type:'EXPRESSION_INTENT',ticker:'ANET',intent:'OWNERSHIP'});expect(r.expression!.finalists.ANET.analysis!.objective.horizon).toBe('18 months');expect(r.lockedThesis!.horizon).toBe('two years');for(const key of ['lockedThesis','discovery','wash1','wash2','wash3','universe','finalists','exclusions','washes'] as const)expect(r[key]).toBe(initial[key]);expect(checkpointReducer(r,{type:'CURATE_WASH3',ticker:'ANET'})).toBe(r)});
 it('makes all three families credible without forcing equal winners and preserves upstream burdens',async()=>{const r=await entered();const anet=r.expression!.finalists.ANET.context,etn=r.expression!.finalists.ETN.context;expect(buildExpression(anet,'CONVEXITY').preferred).toBe('LONG_CALL');expect(buildExpression(anet,'DEFINED_RISK').preferred).toBe('CALL_SPREAD');expect(buildExpression(etn,'CONVEXITY').preferred).toBe('STOCK');expect(buildExpression(etn,'DEFINED_RISK').alternative).toBe('CALL_SPREAD');expect(anet.t1.ve.state).toBe(etn.t1.ve.state);expect(anet.t3.pricedIn).not.toBe(etn.t3.pricedIn);const high=structuredClone(anet);high.t1.ve.state='High burden';expect(buildExpression(high,'CONVEXITY').preferred).toBe('STOCK')});
 it('uses conservative explicit demo intent and leaves unknown preference unspecified',()=>{expect(readDemoIntent('I want common stock, no options')).toBe('OWNERSHIP');expect(readDemoIntent('I accept capped upside for lower premium')).toBe('DEFINED_RISK');expect(readDemoIntent('Asymmetric upside')).toBe('CONVEXITY');expect(readDemoIntent('I am still thinking')).toBe('UNSPECIFIED')});
 it('requires explicit confirmation for every finalist before completing Result',async()=>{let r=reply(await entered());expect(checkpointReducer(r,{type:'READY_FOR_RESULT'})).toBe(r);r=checkpointReducer(r,{type:'CONFIRM_EXPRESSION',ticker:'ANET'});expect(r.expression!.status).toBe('IN_PROGRESS');r=reply(r,'ETN','Direct ownership durability');r=checkpointReducer(r,{type:'CONFIRM_EXPRESSION',ticker:'ETN'});expect(r.expression!.status).toBe('COMPLETE');r=checkpointReducer(r,{type:'READY_FOR_RESULT'});expect(r.result!.status).toBe('RESEARCH_COMPLETE');expect(r.stage).toBe('OUTPUT');expect(r.support).toBeNull();expect(r.caseFor).toBeNull();expect(r.caseAgainst).toBeNull();expect(r.pending).toBeNull()});
 it('inspecting a family preserves confirmation; objective changes require reconfirmation',async()=>{let r=reply(await entered());r=checkpointReducer(r,{type:'CONFIRM_EXPRESSION',ticker:'ANET'});r=checkpointReducer(r,{type:'INSPECT_EXPRESSION_FAMILY',ticker:'ANET',family:'STOCK'});expect(r.expression!.finalists.ANET.confirmed).toBe('LONG_CALL');r=checkpointReducer(r,{type:'EXPRESSION_INTENT',ticker:'ANET',intent:'OWNERSHIP'});expect(r.expression!.finalists.ANET.confirmed).toBeNull();expect(r.expression!.finalists.ANET.confirmationHistory).toEqual([{family:'LONG_CALL',revision:1}])});
 it('rejects blank replies and unknown candidates without progress changes',async()=>{const r=await entered();expect(reply(r,'ANET','  ')).toBe(r);expect(reply(r,'UNKNOWN')).toBe(r);expect(checkpointReducer(r,{type:'SWITCH_EXPRESSION_FINALIST',ticker:'VRT'})).toBe(r);expect(checkpointReducer(r,{type:'CONFIRM_EXPRESSION',ticker:'ANET'})).toBe(r)});
});
describe('Expression conversation and analysis',()=>{
 it('shows inherited context before a short user-dependent question, not a new thesis request',async()=>{render(<Harness initial={await entered()}/>);expect(screen.getByRole('region',{name:'Inherited research context'})).toHaveTextContent('two years');const chat=screen.getByRole('region',{name:'Expression conversation'});expect(chat).toHaveTextContent('Your thesis horizon is two years');expect(chat).not.toHaveTextContent('What is your thesis?');expect(screen.queryByRole('region',{name:'Strategy-family comparison'})).not.toBeInTheDocument()});
 it('Enter sends and unlocks comparison while retaining focus',async()=>{render(<Harness initial={await entered()}/>);const box=screen.getByRole('textbox');await userEvent.type(box,'Asymmetric upside{Enter}');expect(box).toHaveValue('');expect(box).toHaveFocus();expect(screen.getByRole('region',{name:'Strategy-family comparison'})).toBeVisible()});
 it('Shift+Enter inserts a newline and empty Enter cannot submit',async()=>{render(<Harness initial={await entered()}/>);const box=screen.getByRole('textbox');await userEvent.click(box);await userEvent.keyboard('{Enter}   {Enter}');expect(screen.queryByRole('region',{name:'Strategy-family comparison'})).not.toBeInTheDocument();await userEvent.clear(box);await userEvent.type(box,'First thought');await userEvent.keyboard('{Shift>}{Enter}{/Shift}Second thought');expect(box).toHaveValue('First thought\nSecond thought');expect(screen.queryByRole('region',{name:'Strategy-family comparison'})).not.toBeInTheDocument()});
 it('guards IME composition and preserves pointer send',async()=>{render(<Harness initial={await entered()}/>);const box=screen.getByRole('textbox');fireEvent.change(box,{target:{value:'Direct ownership'}});fireEvent.compositionStart(box);fireEvent.keyDown(box,{key:'Enter'});fireEvent.compositionEnd(box);fireEvent.keyDown(box,{key:'Enter',isComposing:true});fireEvent.keyDown(box,{key:'Enter',keyCode:229});expect(screen.queryByRole('region',{name:'Strategy-family comparison'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Send ANET expression preference'}));expect(screen.getByRole('region',{name:'Strategy-family comparison'})).toBeVisible()});
 it.each(expressionFamilies)('renders and allows keyboard inspection of %s with qualitative dimensions',async family=>{render(<Harness initial={reply(await entered())}/>);const button=screen.getByRole('button',{name:'Inspect '+familyNames[family]});button.focus();await userEvent.keyboard('{Enter}');expect(button).toHaveAttribute('aria-pressed','true');const comparison=within(screen.getByRole('region',{name:'Strategy-family comparison'}));for(const label of ['Thesis fit','Horizon fit','Timing tolerance','Path tolerance','Capital intensity','Loss character','Upside participation','Expiration sensitivity','Volatility sensitivity','Complexity','Why it fits this research state','Why it may not'])expect(comparison.getByText(label)).toBeVisible();expect(comparison.queryByText(/score\s*[=:]\s*\d/i)).not.toBeInTheDocument()});
 it('renders a reasoned preference, credible alternative and change conditions',async()=>{render(<Harness initial={reply(await entered())}/>);const preferred=within(screen.getByRole('region',{name:'Preferred demonstration expression'}));expect(preferred.getByText('Long-Duration Call Exposure')).toBeVisible();expect(preferred.getByText('Alternative · Common Stock')).toBeVisible();expect(preferred.getByText(/ANET.*surviving economics/)).toBeVisible();expect(preferred.getByText('Tradeoff')).toBeVisible();fireEvent.click(preferred.getByText('What would change this expression?'));expect(preferred.getByText(/More uncertain or later recognition/)).toBeVisible()});
 it('separates inherited risks from changing structure risks and success conditions',async()=>{render(<Harness initial={reply(await entered())}/>);const risks=within(screen.getByRole('region',{name:'Expression risks'}));expect(risks.getByText('Inherited from the thesis')).toBeVisible();expect(risks.getByText('Created / amplified by the expression')).toBeVisible();expect(risks.getByText(/Deployment cadence:/)).toBeVisible();expect(risks.getByText('Expiration can arrive before recognition.')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Inspect Common Stock'}));expect(risks.getByText('Full downside participation if the security deteriorates.')).toBeVisible();expect(risks.queryByText('Expiration can arrive before recognition.')).not.toBeInTheDocument();expect(screen.getByRole('region',{name:'Expression success conditions'})).toHaveTextContent('ANET · Common Stock');expect(screen.getByLabelText('Demonstration limitations')).toHaveTextContent('No live option chain is connected')});
 it('supports independent finalist switching, editable intent and explicit confirmation',async()=>{render(<Harness initial={reply(await entered())}/>);fireEvent.click(screen.getByRole('button',{name:'Use this expression for ANET'}));expect(screen.getByText('Confirmed for ANET: Long-Duration Call Exposure')).toBeVisible();screen.getByRole('button',{name:'View ETN Expression'}).focus();await userEvent.keyboard('{Enter}');expect(screen.queryByRole('region',{name:'Strategy-family comparison'})).not.toBeInTheDocument();await userEvent.type(screen.getByRole('textbox'),'Defined-risk capital efficiency{Enter}');expect(within(screen.getByRole('region',{name:'Preferred demonstration expression'})).getByText('Common Stock')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Inspect Call Debit Spread'}));fireEvent.click(screen.getByRole('button',{name:'Use this expression for ETN'}));expect(screen.getByRole('button',{name:'Proceed to Result'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Compare ANET expression'}));expect(screen.getByText('Confirmed for ANET: Long-Duration Call Exposure')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Direct ownership durability'}));expect(screen.queryByText('Confirmed for ANET: Long-Duration Call Exposure')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Proceed to Result'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Use this expression for ANET'}));fireEvent.click(screen.getByRole('button',{name:'Proceed to Result'}));expect(screen.getByText('Expression saved. Result preserves these confirmed decisions.')).toBeVisible()});
 it('keeps confirmed downstream state through all historical stages with reduced motion and no requests',async()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:true} as MediaQueryList);Element.prototype.scrollIntoView=vi.fn();const fetch=vi.spyOn(globalThis,'fetch');render(<App/>);await userEvent.type(screen.getByRole('textbox'),'AI infrastructure{Enter}');await waitFor(()=>expect(screen.getByRole('button',{name:'Lock & begin research'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Lock & begin research'}));const header=within(screen.getByLabelText('Research navigation'));for(const stage of ['Wash 1','Wash 2','Wash 3'])fireEvent.click(header.getByRole('button',{name:new RegExp('Proceed to '+stage)}));fireEvent.click(screen.getByRole('checkbox',{name:'Select ANET for Expression'}));fireEvent.click(header.getByRole('button',{name:/Proceed to Expression/}));expect(screen.getByText('Wash 3 · frozen Adversarial Confirmation')).toBeVisible();await userEvent.type(screen.getByRole('textbox'),'Asymmetric upside{Enter}');fireEvent.click(screen.getByRole('button',{name:'Use this expression for ANET'}));for(const stage of ['Thesis','Discovery','Wash 1','Wash 2','Wash 3','Expression']){fireEvent.click(header.getByRole('button',{name:'View saved '+stage}));expect(screen.getByText('Viewing saved '+stage+' · Research: Expression')).toBeVisible();expect(header.getByRole('button',{name:'Proceed to Result'})).toBeEnabled()}expect(screen.getByText('Confirmed for ANET: Long-Duration Call Exposure')).toBeVisible();fireEvent.click(header.getByRole('button',{name:'Proceed to Result'}));expect(screen.getByRole('region',{name:'Completed research output'})).toBeVisible();expect(header.getByRole('button',{name:'View saved Result'})).toBeEnabled();expect(fetch).not.toHaveBeenCalled()},15000);
});
