import {describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,within} from '@testing-library/react';
import App from '../App';
import {initialMember,memberReducer,sampleResearch,you,leaderboard,cohort} from '../member/model';
Element.prototype.scrollIntoView=vi.fn();
describe('session-only member boundaries',()=>{
 it('keeps ownership and sharing isolated to the selected group',()=>{let s=initialMember();const own=sampleResearch.find(r=>r.owner===you)!;expect(s.groups[0].shares.some(r=>r.owner===you)).toBe(false);s=memberReducer(s,{type:'CREATE_GROUP',name:'My circle',description:''});s=memberReducer(s,{type:'SHARE',groupId:'local-2',research:own});expect(s.groups[0].shares.some(r=>r.id===own.id)).toBe(false);expect(s.groups[1].shares[0].owner).toBe(you);expect(s.groups[1].members).toEqual([you]);const denied=memberReducer(s,{type:'SHARE',groupId:'local-2',research:sampleResearch[2]});expect(denied).toBe(s);s=memberReducer(s,{type:'UNSHARE',groupId:'local-2',researchId:own.id});expect(s.groups[1].shares).toEqual([]);expect(own.thesis).toBe(sampleResearch[0].thesis)});
 it('ranks only shared comparable samples on separate instrument boards',()=>{const g=initialMember().groups[0];const ids=g.shares.map(r=>r.id);const underlying=leaderboard('underlying',g.members,ids);const expression=leaderboard('expression',g.members,ids);expect(underlying).toHaveLength(3);expect(expression).toHaveLength(2);expect(underlying.some(e=>e.researchId==='sample-power')).toBe(false);expect(expression.every(e=>e.expression!==null)).toBe(true);expect(underlying[0].underlying).toBeGreaterThan(underlying[1].underlying);expect(cohort).toMatchObject({capital:10000,start:'2025-01-02',end:'2025-03-31'});expect(leaderboard('underlying',g.members,[])).toEqual([])});
 it('returns to the same research state after creating and sharing with a group',async()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:true} as MediaQueryList);render(<App/>);fireEvent.change(screen.getByRole('textbox'),{target:{value:'AI infrastructure needs power'}});fireEvent.click(screen.getByRole('button',{name:'Begin thesis conversation'}));fireEvent.click(await screen.findByRole('button',{name:'Lock & begin research'}));expect(await screen.findByText(/9 examined · 7 validated/)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Exclude VRT'}));const nav=screen.getByRole('navigation',{name:'Member navigation'});fireEvent.click(within(nav).getByRole('button',{name:'Groups'}));fireEvent.click(screen.getByText('Create a group',{selector:'summary'}));fireEvent.change(screen.getByLabelText('Group name'),{target:{value:'Private circle'}});fireEvent.click(screen.getByRole('button',{name:'Create demo group'}));fireEvent.click(screen.getByText('Share one of my theses',{selector:'summary'}));fireEvent.click(screen.getByRole('button',{name:'Share snapshot in demo'}));expect(screen.getByRole('heading',{name:'Current thesis'})).toBeVisible();expect(screen.getByText('You (demo)',{selector:'.shared-feed .card-top span'})).toBeVisible();fireEvent.click(within(nav).getByRole('button',{name:'Current ResearchRun'}));expect(screen.getByRole('button',{name:'Re-include VRT'})).toBeVisible();expect(screen.getByText('candidates will proceed').querySelector('b')).toHaveTextContent('6');vi.restoreAllMocks()});
});
