import {describe,it,expect,vi,afterEach} from 'vitest';
import {render,screen,fireEvent,within,waitFor,act} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {useReducer} from 'react';
import {initialCheckpoint,checkpointReducer,localAssistant,type CheckpointRun} from '../checkpoint/research';
import {discoveryEvents} from '../discovery/fixtures';
import {wash1Events,wash1Fixtures} from '../wash1/fixtures';
import {wash1Count} from '../wash1/model';
import {Wash1Experience} from '../wash1/Wash1Experience';
import App from '../App';
async function discovery(){let r=initialCheckpoint();const response=await localAssistant.respond({message:'AI infrastructure',thesis:null});r=checkpointReducer(r,{type:'REPLY',input:'AI infrastructure',response});r=checkpointReducer(r,{type:'LOCK'});return discoveryEvents.reduce((r,event)=>checkpointReducer(r,{type:'DISCOVERY_EVENT',event}),r)}
const finish=(r:CheckpointRun)=>wash1Events.reduce((r,_,index)=>checkpointReducer(r,{type:'WASH1_EVENT',index}),r);
function Harness({initial}:{initial:CheckpointRun}){const [run,dispatch]=useReducer(checkpointReducer,initial);return <Wash1Experience run={run} dispatch={dispatch}/>}
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks()});
describe('Wash 1 normalized state',()=>{
 it('freezes only curated Discovery participants, including Recall lineage',async()=>{let r=await discovery();r=checkpointReducer(r,{type:'CURATE_DISCOVERY',ticker:'VRT'});const d=r.discovery;r=checkpointReducer(r,{type:'START_WASH1'});expect(r.stage).toBe('WASH_1');expect(r.wash1!.participants).toHaveLength(6);expect(r.wash1!.participants).not.toContain('VRT');expect(r.wash1!.discovery.PWR.candidate.recall).toBe(true);expect(r.universe.PWR.trajectory[0].t).toBe(0);expect(checkpointReducer(r,{type:'START_WASH1'})).toBe(r);expect(checkpointReducer(r,{type:'CURATE_DISCOVERY',ticker:'VRT'})).toBe(r);expect(d!.candidates.VRT.userState).toBe('USER_EXCLUDED')});
 it('rejects out-of-order events and compares only after independent freezes',async()=>{let r=checkpointReducer(await discovery(),{type:'START_WASH1'});expect(checkpointReducer(r,{type:'WASH1_EVENT',index:16})).toBe(r);for(let index=0;index<wash1Events.length;index++){r=checkpointReducer(r,{type:'WASH1_EVENT',index});if(index===6){expect(r.wash1!.economicFrozen).toBe(true);expect(r.wash1!.marketFrozen).toBe(false)}if(index===15){expect(r.wash1!.marketFrozen).toBe(true);expect(r.wash1!.comparisonComplete).toBe(false)}}expect(r.wash1!.status).toBe('COMPLETE');expect(r.activity.slice(-20).map(e=>e.type)).toEqual(wash1Events.map(e=>e.type));expect(r.universe.PWR.trajectory.map(p=>p.t)).toEqual([0,1]);expect(r.washes).toHaveLength(1);expect(r).toEqual(finish(checkpointReducer(await discovery(),{type:'START_WASH1'})))});
 it('retains frozen T0/T1 and dispositions while curation changes only decisions',async()=>{let r=finish(checkpointReducer(await discovery(),{type:'START_WASH1'}));const result=r.wash1!.results.VRT;expect(wash1Count(r.wash1!)).toBe(5);r=checkpointReducer(r,{type:'CURATE_WASH1',ticker:'VRT'});expect(wash1Count(r.wash1!)).toBe(4);expect(r.wash1!.results.VRT).toBe(result);expect(r.universe.VRT.userExcluded).toBe(true);expect(r.exclusions.at(-1)?.stage).toBe('WASH_1');expect(r.wash1!.results.AMD.disposition).toBe('REVIEW');expect(r.wash1!.results.AMAT.disposition).toBe('HOLD');r=checkpointReducer(r,{type:'CURATE_WASH1',ticker:'VRT'});expect(wash1Count(r.wash1!)).toBe(5);r=checkpointReducer(r,{type:'READY_FOR_WASH2'});expect(r.stage).toBe('WASH_1');expect(r.washes).toHaveLength(1);expect(r.wash1!.readyForWash2).toBe(true);expect(r.wash1!.decisions).toHaveLength(2)});
 it('contains contrasting lenses without deriving one state from another',()=>{expect(new Set(Object.values(wash1Fixtures).map(r=>r.gap)).size).toBe(5);expect(wash1Fixtures.ETN.cf.state).toBe('Weak');expect(wash1Fixtures.ETN.economic.state).toBe('Strong');expect(wash1Fixtures.AMD.gap).toBe('NEGATIVE GAP');expect(wash1Fixtures.PWR.dm.confidence).toBe('Low');expect(wash1Fixtures.PWR.dm.state).toBe('Strong');expect(wash1Fixtures.ETN.regime).toBe('Compression');expect(wash1Fixtures.AMD.regime).toBe('Expansion');expect(new Set(Object.values(wash1Fixtures).map(r=>r.t1.why)).size).toBe(7)});
});
describe('Wash 1 continuous interaction',()=>{
 it('runs deterministic events sequentially and skip reaches the same result',async()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:false} as MediaQueryList);const initial=checkpointReducer(await discovery(),{type:'START_WASH1'});vi.useFakeTimers();render(<Harness initial={initial}/>);for(let i=0;i<3;i++){act(()=>vi.advanceTimersByTime(240));expect(screen.getByRole('status')).toHaveTextContent(wash1Events[i].message)}fireEvent.click(screen.getByRole('button',{name:'Show complete Wash 1 demonstration'}));expect(screen.getByText('Wash 1 complete · T1 · local demonstration')).toBeVisible();expect(screen.getByText(/20 Wash 1 activity events/)).toBeVisible();expect(screen.getByText('5 candidates eligible for Wash 2')).toBeVisible()});
 it('coordinates map, trajectory, details, contradictions and curation with keyboard',async()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:true} as MediaQueryList);const fetch=vi.spyOn(globalThis,'fetch');render(<Harness initial={checkpointReducer(await discovery(),{type:'START_WASH1'})}/>);
 const map=screen.getByRole('region',{name:'Economic Reality × Market Recognition map'});const etn=within(map).getByRole('button',{name:'Select ETN reality and recognition'});etn.focus();await userEvent.keyboard('{Enter}');expect(etn).toHaveAttribute('aria-pressed','true');expect(screen.getByRole('button',{name:'Select ETN trajectory'})).toHaveAttribute('aria-pressed','true');expect(screen.getByRole('button',{name:'Select ETN Wash 1 summary'}).parentElement).toHaveClass('selected');expect(screen.getByText(wash1Fixtures.ETN.t1.why)).toBeVisible();fireEvent.click(screen.getByText('How to read the discrepancy'));expect(screen.getByText(/not proof of mispricing/)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Inspect ETN · Discovery + Wash 1'}));const dialog=screen.getByRole('dialog');for(const label of ['FQ-01','DM-01','CF-01','VE-01','TR-01'])expect(within(dialog).getByText(new RegExp(label))).toBeVisible();expect(within(dialog).getByText(/Volume Cycle · RESET → DORMANT/)).toBeVisible();expect(within(dialog).getByLabelText('Demonstration technical regime: Compression')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Close candidate detail'}));fireEvent.click(screen.getByRole('button',{name:'Select AMD trajectory'}));expect(within(map).getByRole('button',{name:'Select AMD reality and recognition'})).toHaveAttribute('aria-pressed','true');expect(screen.getByText(wash1Fixtures.AMD.contradictions[0])).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Exclude ETN from Wash 1'}));expect(screen.getByRole('button',{name:'Select ETN trajectory'})).toBeVisible();expect(screen.getByText('4 candidates eligible for Wash 2')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Re-include ETN from Wash 1'}));expect(screen.getByText('5 candidates eligible for Wash 2')).toBeVisible();expect(fetch).not.toHaveBeenCalled()});
 it('updates sticky count and preserves selection and history across historical navigation',async()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:true} as MediaQueryList);Element.prototype.scrollIntoView=vi.fn();render(<App/>);await userEvent.type(screen.getByRole('textbox'),'AI infrastructure{Enter}');await waitFor(()=>expect(screen.getByRole('button',{name:'Lock & begin research'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Lock & begin research'}));const header=screen.getByLabelText('Research navigation');fireEvent.click(within(header).getByRole('button',{name:/Proceed to Wash 1/}));const proceed=within(header).getByRole('button',{name:/Proceed to Wash 2/});expect(proceed).toHaveTextContent('5 candidates');fireEvent.click(screen.getByRole('button',{name:'Select PWR trajectory'}));expect(screen.getByRole('region',{name:'Selected Wash 1 candidate'})).toHaveTextContent('Entered through Discovery Recall');fireEvent.click(screen.getByRole('button',{name:'Exclude PWR from Wash 1'}));expect(proceed).toHaveTextContent('4 candidates');for(const stage of ['Thesis','Discovery','Wash 1'])fireEvent.click(screen.getByRole('button',{name:'View saved '+stage}));expect(screen.getByRole('button',{name:'Select PWR trajectory'})).toHaveAttribute('aria-pressed','true');expect(screen.getByRole('button',{name:'Re-include PWR from Wash 1'})).toBeVisible();expect(screen.getByText(/20 Wash 1 activity events/)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Re-include PWR from Wash 1'}));expect(proceed).toHaveTextContent('5 candidates');fireEvent.click(proceed);expect(screen.getByRole('region',{name:'Wash 2 research canvas'})).toBeVisible();expect(screen.getByRole('button',{name:'Not yet available: Wash 3'})).toBeDisabled();expect(screen.getByText('Viewing saved Wash 2 · Research: Wash 2')).toBeVisible()},15000);
});
