import {useReducer} from 'react';
import {describe,it,expect,vi,afterEach} from 'vitest';
import {render,screen,within,fireEvent,act,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../App';
import {initialCheckpoint,checkpointReducer,localAssistant,type CheckpointRun} from '../checkpoint/research';
import {discoveryEvents} from '../discovery/fixtures';
import {wash1Events} from '../wash1/fixtures';
import {wash2Events} from '../wash2/fixtures';
import {wash3Events,wash3Fixtures} from '../wash3/fixtures';
import {finalistEligible,selectedFinalists} from '../wash3/model';
import {Wash3Experience} from '../wash3/Wash3Experience';
async function wash2(){let r=initialCheckpoint();r=checkpointReducer(r,{type:'REPLY',input:'AI infrastructure',response:await localAssistant.respond({message:'AI infrastructure',thesis:null})});r=checkpointReducer(r,{type:'LOCK'});for(const event of discoveryEvents)r=checkpointReducer(r,{type:'DISCOVERY_EVENT',event});r=checkpointReducer(r,{type:'START_WASH1'});for(let index=0;index<wash1Events.length;index++)r=checkpointReducer(r,{type:'WASH1_EVENT',index});r=checkpointReducer(r,{type:'START_WASH2'});for(let index=0;index<wash2Events.length;index++)r=checkpointReducer(r,{type:'WASH2_EVENT',index});return r}
const finish=(r:CheckpointRun)=>wash3Events.reduce((r,_,index)=>checkpointReducer(r,{type:'WASH3_EVENT',index}),r);
async function completed(){return finish(checkpointReducer(await wash2(),{type:'START_WASH3'}))}
function Harness({initial}:{initial:CheckpointRun}){const [run,dispatch]=useReducer(checkpointReducer,initial);return <Wash3Experience run={run} dispatch={dispatch}/>}
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks()});
describe('Wash 3 ResearchRun continuity and firewall',()=>{
 it('enters only from a completed, nonempty Wash 2 universe',async()=>{expect(checkpointReducer(initialCheckpoint(),{type:'START_WASH3'}).wash3).toBeNull();let r=await wash2();expect(checkpointReducer(r,{type:'START_WASH3'}).wash3!.participants).toEqual(['ANET','VRT','ETN']);for(const ticker of ['ANET','VRT','ETN'])r=checkpointReducer(r,{type:'CURATE_WASH2',ticker});expect(checkpointReducer(r,{type:'START_WASH3'})).toBe(r)});
 it('preserves exclusions, Recall lineage and immutable T0/T1/T2 snapshots',async()=>{let r=await wash2();r=checkpointReducer(r,{type:'CURATE_WASH2',ticker:'ETN'});const prior=structuredClone(r);r=checkpointReducer(r,{type:'START_WASH3'});expect(r.stage).toBe('WASH_3');expect(r.wash3!.participants).toEqual(['ANET','VRT']);expect(r.wash3!.prior).toEqual(prior.wash2);r=finish(r);expect(r.universe.ETN).toEqual(prior.universe.ETN);expect(r.wash1!.discovery.PWR.candidate.recall).toBe(true);expect(r.discovery).toEqual(prior.discovery);expect(r.wash1).toEqual(prior.wash1);expect(r.universe.ANET.trajectory.slice(0,3)).toEqual(prior.universe.ANET.trajectory);expect(r.universe.ANET.trajectory.map(p=>p.t)).toEqual([0,1,2,3]);expect(checkpointReducer(r,{type:'CURATE_WASH2',ticker:'ETN'})).toBe(r);expect(checkpointReducer(r,{type:'START_WASH3'})).toBe(r)});
 it('rejects out-of-order and duplicate events and has identical accelerated state',async()=>{const initial=checkpointReducer(await wash2(),{type:'START_WASH3'});expect(checkpointReducer(initial,{type:'WASH3_EVENT',index:4})).toBe(initial);let partial=initial;for(let index=0;index<4;index++)partial=checkpointReducer(partial,{type:'WASH3_EVENT',index});const r=finish(partial);expect(r).toEqual(finish(initial));expect(r.activity.slice(-15).map(e=>e.type)).toEqual(wash3Events.map(e=>e.type));expect(r.washes.map(w=>w.stage)).toEqual(['WASH_1','WASH_2','WASH_3']);expect(checkpointReducer(r,{type:'WASH3_EVENT',index:14})).toBe(r);expect(r.wash3!.results.ANET.lineage.prior).toBe('WASH_2_T2')});
 it('starts with no selections and stores explicit selection and deselection',async()=>{let r=await completed();expect(selectedFinalists(r.wash3!)).toEqual([]);r=checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'ANET'});expect(r.finalists.find(f=>f.ticker==='ANET')?.selected).toBe(true);r=checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'ANET'});expect(selectedFinalists(r.wash3!)).toEqual([]);expect(r.wash3!.decisions.map(d=>d.decision)).toEqual(['SELECTED','DESELECTED'])});
 it('enforces upstream failures independently of a claimed eligible status',async()=>{const r=await completed();for(const override of [{status:'THESIS FAILURE' as const},{verdict:'THESIS FAILURE' as const},{causalIntact:false},{integrity:{...r.wash3!.results.ANET.integrity,sufficient:false}},{t3:{...r.wash3!.results.ANET.t3,disposition:'THESIS_FAILURE' as const}},{status:'HELD' as const}]){const altered=structuredClone(r);altered.wash3!.results.ANET={...altered.wash3!.results.ANET,...override};expect(finalistEligible(altered.wash3!.results.ANET)).toBe(false);expect(checkpointReducer(altered,{type:'SELECT_FINALIST',ticker:'ANET'})).toBe(altered)}expect(checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'VRT'})).toBe(r);expect(checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'UNKNOWN'})).toBe(r)});
 it('exclusion clears selection without erasing research or silently restoring it',async()=>{let r=await completed();const history=r.universe.ANET.trajectory;r=checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'ANET'});r=checkpointReducer(r,{type:'CURATE_WASH3',ticker:'ANET'});expect(selectedFinalists(r.wash3!)).toEqual([]);expect(r.universe.ANET.trajectory).toBe(history);expect(r.exclusions.at(-1)?.stage).toBe('WASH_3');expect(checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'ANET'})).toBe(r);r=checkpointReducer(r,{type:'CURATE_WASH3',ticker:'ANET'});expect(selectedFinalists(r.wash3!)).toEqual([])});
 it('saves finalists without executing Expression and invalidates the stop when selection changes',async()=>{let r=await completed();expect(checkpointReducer(r,{type:'SAVE_FINALISTS'})).toBe(r);r=checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'ETN'});r=checkpointReducer(r,{type:'SAVE_FINALISTS'});expect(r.wash3!.finalistsSaved).toBe(true);expect(r.stage).toBe('WASH_3');expect(r.expressions).toEqual([]);expect(r.pending).toBeNull();r=checkpointReducer(r,{type:'SELECT_FINALIST',ticker:'ANET'});expect(r.wash3!.finalistsSaved).toBe(false)});
 it('retains different movements, confidence, conflicts and conditions without a final score',()=>{const rows=Object.values(wash3Fixtures);expect(new Set(rows.map(r=>r.verdict)).size).toBe(3);expect(rows.filter(finalistEligible)).toHaveLength(2);expect(wash3Fixtures.VRT.status).toBe('SURVIVES — REVIEW');expect(wash3Fixtures.ANET.integrity.confidence).toBe('Moderate');expect(wash3Fixtures.ETN.integrity.confidence).toBe('High');expect(wash3Fixtures.ANET.t3.rap).toBeLessThan(76);expect(wash3Fixtures.ETN.t3.rap).toBeGreaterThan(72);expect(wash3Fixtures.VRT.t3.ops).toBeLessThan(81);for(const r of rows){expect(r.integrity.conflicts.conflicting).toBeTruthy();expect(r.unresolved).toBeTruthy();expect(r).not.toHaveProperty('score');expect(r).not.toHaveProperty('probability')}});
});
describe('Wash 3 analytical surfaces',()=>{
 it.each(['Adversarial Review','Case For and Case Against','Specific challenges','Alternative Explanation','Expectations and timing','Evidence Integrity','Comparative Synthesis','T0 to T3 trajectories','Final survivor selection'])('renders %s with candidate context',async(name)=>{render(<Harness initial={await completed()}/>);expect(screen.getByRole('region',{name})).toBeVisible()});
 it('exposes attacked, survived, weakened and unresolved rather than hiding them in detail',async()=>{render(<Harness initial={await completed()}/>);const focus=within(screen.getByRole('region',{name:'Adversarial Review'}));for(const label of ['Original surviving thesis','What Fidelis attacked','What survived','What weakened','What remains unresolved'])expect(focus.getByText(label)).toBeVisible();expect(focus.getByText(wash3Fixtures.ANET.weakened)).toBeVisible();const cases=within(screen.getByRole('region',{name:'Case For and Case Against'}));expect(cases.getByText('Case For')).toBeVisible();expect(cases.getByText('Case Against')).toBeVisible()});
 it('keeps alternative discrimination, inherited expectations and directional/timing states explicit',async()=>{render(<Harness initial={await completed()}/>);expect(screen.getByText(wash3Fixtures.ANET.alternative.distinguish)).toBeVisible();expect(screen.getByText('What may already be priced in?')).toBeVisible();expect(screen.getByText('Inherited VE / Expectations · Moderate burden · Stable')).toBeVisible();const scope=within(screen.getByRole('region',{name:'Expectations and timing'}));expect(scope.getByText('Thesis direction')).toBeVisible();expect(scope.getByText('Timing')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Select VRT adversarial review'}));expect(scope.getByText('Supported with conditions')).toBeVisible();expect(scope.getByText('UNCERTAIN')).toBeVisible()});
 it('keeps confidence distinct, conflicts visible and comparative tradeoffs multidimensional',async()=>{render(<Harness initial={await completed()}/>);const ei=within(screen.getByRole('region',{name:'Evidence Integrity'}));for(const label of ['Authority','Freshness','Point-in-time integrity','Missing evidence','Reproducibility','Overall confidence','Key limitation','Supporting evidence','Conflicting evidence'])expect(ei.getByText(label)).toBeVisible();expect(ei.getByText(/Evidence confidence: Moderate. Thesis survival: STRONG/)).toBeVisible();const sy=within(screen.getByRole('region',{name:'Comparative Synthesis'}));for(const label of ['Economic Reality','Market Recognition','Causal strength','Principal fragility','Adversarial survival','Evidence confidence','Expectations burden','Timing'])expect(sy.getByText(label)).toBeVisible();expect(sy.getByText(wash3Fixtures.ANET.comparative.disagreement)).toBeVisible();expect(screen.queryByText(/Final Fidelis score/i)).not.toBeInTheDocument()});
 it('coordinates keyboard challenge, tradeoff, trajectory and survivor selection without hover',async()=>{render(<Harness initial={await completed()}/>);screen.getByRole('button',{name:'Compare ETN tradeoffs'}).focus();await userEvent.keyboard('{Enter}');expect(screen.getByRole('button',{name:'Select ETN adversarial review'})).toHaveAttribute('aria-pressed','true');expect(screen.getByRole('button',{name:'Select ETN T0 to T3 trajectory'})).toHaveAttribute('aria-pressed','true');screen.getByRole('button',{name:/Inspect ETN challenge 2:/}).focus();await userEvent.keyboard('{Enter}');expect(screen.getByText('Finalist eligibility survives without a recognition-date claim.')).toBeVisible();expect(screen.getAllByText(wash3Fixtures.ETN.t3.why)[0]).toBeVisible();fireEvent.click(screen.getByText('Complete trajectory story · T0 → T1 → T2 → T3'));expect(screen.getByText('T3 · 83 OPS / 75 RAP')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Inspect VRT final survivor'}));expect(screen.getByRole('button',{name:'Compare VRT tradeoffs'})).toHaveAttribute('aria-pressed','true');fireEvent.click(screen.getByRole('button',{name:'Inspect VRT · complete research history'}));const dialog=within(screen.getByRole('dialog'));expect(dialog.getByText('Wash 3 · Adversarial Confirmation · T3')).toBeVisible();expect(dialog.getByText(/Lineage: alpha-003-wash3-v1/)).toBeVisible()});
 it('selects, deselects and saves finalists with dynamic counts and a blocked review candidate',async()=>{render(<Harness initial={await completed()}/>);expect(screen.getByRole('checkbox',{name:'Select VRT for Expression'})).toBeDisabled();const c=screen.getByRole('checkbox',{name:'Select ANET for Expression'});c.focus();await userEvent.keyboard(' ');expect(c).toBeChecked();expect(screen.getByRole('button',{name:'Proceed to Expression · 1 selected'})).toBeEnabled();fireEvent.click(c);expect(screen.getByRole('button',{name:'Proceed to Expression · 0 selected'})).toBeDisabled();fireEvent.click(c);fireEvent.click(screen.getByRole('button',{name:'Exclude ANET from Wash 3'}));expect(c).not.toBeChecked();expect(c).toBeDisabled();expect(screen.getByRole('button',{name:'Select ANET T0 to T3 trajectory'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Re-include ANET from Wash 3'}));fireEvent.click(c);fireEvent.click(screen.getByRole('button',{name:'Proceed to Expression · 1 selected'}));expect(screen.getByText('Finalists saved. Expression preserves this research and your selection.')).toBeVisible()});
 it('renders failure and held history but blocks selection',async()=>{const r=await completed();r.wash3!.results.VRT.status='THESIS FAILURE';r.wash3!.results.VRT.verdict='THESIS FAILURE';r.wash3!.results.ANET.status='HELD';render(<Harness initial={r}/>);expect(screen.getByRole('checkbox',{name:'Select VRT for Expression'})).toBeDisabled();expect(screen.getByRole('checkbox',{name:'Select ANET for Expression'})).toBeDisabled();expect(screen.getByRole('button',{name:'Select VRT T0 to T3 trajectory'})).toBeEnabled();expect(screen.getByRole('button',{name:'Inspect VRT final survivor'})).toHaveTextContent('THESIS FAILURE')});
 it('executes deterministic activity and skip reaches the same completion',async()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:false} as MediaQueryList);const initial=checkpointReducer(await wash2(),{type:'START_WASH3'});vi.useFakeTimers();render(<Harness initial={initial}/>);for(let i=0;i<3;i++){act(()=>vi.advanceTimersByTime(240));expect(screen.getByRole('status')).toHaveTextContent(wash3Events[i].message)}fireEvent.click(screen.getByRole('button',{name:'Show complete Wash 3 demonstration'}));expect(screen.getByText('15 Wash 3 activity events · review history')).toBeVisible();expect(screen.getByText('Wash 3 complete · T3 · local demonstration')).toBeVisible()});
 it('preserves all stages, selection and progress on historical navigation with reduced motion and no network',async()=>{vi.spyOn(window,'matchMedia').mockReturnValue({matches:true} as MediaQueryList);Element.prototype.scrollIntoView=vi.fn();const fetch=vi.spyOn(globalThis,'fetch');render(<App/>);await userEvent.type(screen.getByRole('textbox'),'AI infrastructure{Enter}');await waitFor(()=>expect(screen.getByRole('button',{name:'Lock & begin research'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Lock & begin research'}));const header=within(screen.getByLabelText('Research navigation'));for(const stage of ['Wash 1','Wash 2','Wash 3'])fireEvent.click(header.getByRole('button',{name:new RegExp('Proceed to '+stage)}));expect(screen.getByText('Wash 2 · frozen Thesis Survival')).toBeVisible();expect(screen.getByRole('region',{name:'Wash 2 research canvas',hidden:true})).not.toBeVisible();fireEvent.click(screen.getByRole('checkbox',{name:'Select ETN for Expression'}));fireEvent.click(screen.getByRole('button',{name:'Select ETN adversarial review'}));const history=screen.getByText('15 Wash 3 activity events · review history').textContent;for(const stage of ['Thesis','Discovery','Wash 1','Wash 2','Wash 3']){header.getByRole('button',{name:'View saved '+stage}).focus();await userEvent.keyboard('{Enter}');expect(screen.getByText('Viewing saved '+stage+' · Research: Wash 3')).toBeVisible();expect(header.getByRole('button',{name:'Proceed to Expression · 1 selected'})).toBeEnabled()}expect(screen.getByRole('checkbox',{name:'Select ETN for Expression'})).toBeChecked();expect(screen.getByRole('button',{name:'Select ETN adversarial review'})).toHaveAttribute('aria-pressed','true');expect(screen.getByText(history!)).toBeVisible();fireEvent.click(header.getByRole('button',{name:'Proceed to Expression · 1 selected'}));expect(screen.getByRole('region',{name:'Expression canvas'})).toBeVisible();expect(header.getByRole('button',{name:'View saved Expression'})).toBeEnabled();expect(header.getByRole('button',{name:'Not yet available: Result'})).toBeDisabled();expect(fetch).not.toHaveBeenCalled()},15000);
});
