import {useEffect,useReducer,useRef,useState,type ReactNode} from 'react';
import {PanelLeftClose,PanelLeftOpen,BookOpen,FlaskConical,Users,ArrowLeft,Menu,X} from 'lucide-react';
import type {CheckpointRun} from '../checkpoint/research';
import {initialMember,memberReducer,type MemberView} from './model';
import {MemberSpace} from './MemberSpace';
import './member.css';
export function MemberShell({active,run,children}:{active:boolean;run:CheckpointRun;children:ReactNode}){
 const [view,setView]=useState<MemberView>('run');const [expanded,setExpanded]=useState(true);const [mobileOpen,setMobileOpen]=useState(false);const [state,dispatch]=useReducer(memberReducer,undefined,initialMember);const drawer=useRef<HTMLDialogElement>(null);const menu=useRef<HTMLButtonElement>(null);const scroll=useRef(0);const previousView=useRef(view);
 function go(next:MemberView){if(next===view){setMobileOpen(false);return}if(view==='run')scroll.current=window.scrollY;setView(next);setMobileOpen(false)}
 useEffect(()=>{if(previousView.current===view)return;previousView.current=view;if(view==='run'){window.scrollTo({top:scroll.current,behavior:'instant'});document.getElementById('continuous-canvas')?.focus({preventScroll:true})}else{window.scrollTo({top:0,behavior:'instant'});document.getElementById('member-content')?.focus({preventScroll:true})}},[view]);
 useEffect(()=>{if(!mobileOpen)return;const el=drawer.current!;const overflow=document.body.style.overflow;el.showModal();document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=overflow;menu.current?.focus({preventScroll:true})}},[mobileOpen]);
 const links=[{id:'run' as const,label:'Current ResearchRun',Icon:ArrowLeft},{id:'research' as const,label:'My Research',Icon:BookOpen},{id:'experiments' as const,label:'My Experiments',Icon:FlaskConical},{id:'groups' as const,label:'Groups',Icon:Users}];
 function nav(){return <nav aria-label="Member navigation">{links.map(({id,label,Icon})=><button key={id} aria-label={label} aria-current={view===id?'page':undefined} onClick={()=>go(id)} title={label}><Icon aria-hidden="true" size={19}/><span>{label}</span></button>)}</nav>}
 return <div className={active?`member-shell ${expanded?'sidebar-expanded':'sidebar-collapsed'}`:'opening-shell'}>{active&&<><aside className="member-sidebar" aria-label="Member sidebar"><img className="member-logo" src={`${import.meta.env.BASE_URL}fidelis-logo.svg`} alt="Fidelis"/><button className="sidebar-toggle" aria-label={expanded?'Collapse sidebar':'Expand sidebar'} aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?<PanelLeftClose size={19}/>:<PanelLeftOpen size={19}/>}</button>{nav()}<p className="sidebar-note">Your research stays yours.</p></aside><div className="member-mobile-bar"><button ref={menu} aria-label="Open member menu" aria-expanded={mobileOpen} aria-controls="member-mobile-menu" onClick={()=>setMobileOpen(true)}><Menu size={22}/></button><img src={`${import.meta.env.BASE_URL}fidelis-logo.svg`} alt="Fidelis"/><span>FIDELIS</span></div><dialog ref={drawer} id="member-mobile-menu" className="member-mobile-menu" aria-label="Member menu" onCancel={e=>{e.preventDefault();setMobileOpen(false)}} onClick={e=>{if(e.target===e.currentTarget)setMobileOpen(false)}}><button autoFocus className="mobile-menu-close" aria-label="Close member menu" onClick={()=>setMobileOpen(false)}><X size={23}/></button><img src={`${import.meta.env.BASE_URL}fidelis-logo.svg`} alt="Fidelis"/>{nav()}<p>Your research stays yours.<br/>Session-only demonstration.</p></dialog><span className="member-demo">DEMO · session only</span></>}
 <div className="research-session" hidden={active&&view!=='run'}>{children}</div>{active&&view!=='run'&&<MemberSpace view={view} run={run} state={state} dispatch={dispatch} returnToRun={()=>go('run')}/>}
 </div>
}
