import type {CandidateT3State,Wash3EventType} from './model';
import type {ResearchActivityEvent} from '../discovery/model';
// Invented normalized results, not current company research, probabilities or private methodology.
const lineage={fixtureVersion:'alpha-003-wash3-v1',source:'SANITIZED_FIXTURE',prior:'WASH_2_T2',liveData:false} as const;
export const wash3Fixtures:Record<string,CandidateT3State>={
 ANET:{ticker:'ANET',verdict:'CHALLENGE RAISED — THESIS SURVIVES',
 challenged:'Repeat networking demand does not establish that the market has underestimated it.',
 survived:'Staggered network deployments still connect infrastructure spending to repeat orders and cash conversion.',
 weakened:'The claim of broad underrecognition weakens when expanding participation can also reflect positioning.',
 unresolved:'Customer concentration and the persistence of participation beyond a deployment cycle remain unresolved.',
 caseFor:['Repeat deployments support durable causal transmission rather than one isolated project.','The frozen economic state strengthened before participation became fully confirmed.'],
 caseAgainst:['A concentrated customer group can defer network orders together.','Moderate embedded expectations still require growth; emerging recognition is not undiscovered demand.'],
 challenges:[{title:'Recognition or positioning?',why:'The thesis needs economic conversion as well as market interest.',support:'The frozen volume cycle moved from Emerging to Expanding while expectations already embed growth.',survived:'Repeat deployments preserve the economic path.',resolution:'Retain a finalist, but reduce confidence in the size of the recognition opportunity.'},{title:'Concentrated deployment calendars',why:'Staggered orders may become synchronized delays if shared capex slows.',support:'Wash 2 retained deployment cadence and hyperscaler capex dependencies.',survived:'Repeat orders are more durable than a single construction award.',resolution:'Concentration remains an explicit condition, not an absorbed risk.'}],
 alternative:{primary:'Broadening participation reflects emerging recognition of improving networking economics.',alternative:'Positioning around AI infrastructure may explain some participation before cash conversion confirms it.',distinguish:'Persistent participation alongside repeated order-to-cash conversion would favor recognition; fading participation without economic deterioration would favor positioning.'},
 pricedIn:'The inherited moderate burden already assumes growth. Strong execution can validate expectations without delivering equally strong additional recognition.',
 timing:{direction:'Supported',state:'BALANCED',reason:'Repeat deployments support the horizon, but recognition can run ahead of the next cash-conversion cycle.'},
 integrity:{authority:'High',freshness:'Frozen demonstration snapshot',pointInTime:'T0–T2 retained; no later observations inserted',conflicts:{supporting:'Repeat orders support the economic thesis.',conflicting:'Expanding participation can reflect positioning as well as durable recognition.'},missing:'Customer-level deployment schedules',reproducibility:'Deterministic fixture and preserved T0–T3 coordinates',confidence:'Moderate',limitation:'Customer-level exposure cannot be decomposed from the illustrative evidence.',sufficient:true},
 comparative:{strength:'Repeat causal transmission',tradeoff:'Customer concentration and closing recognition gap',conclusion:'Networking retains a clear economic path, but less room for recognition than the original interpretation implied.',disagreement:'AR weakens underrecognition; EI remains Moderate; SY retains eligibility because repeat transmission survives.'},
 status:'FINALIST ELIGIBLE',causalIntact:true,t3:{t:3,ops:80,rap:69,why:'OPS remains 80 because repeat networking demand survives. RAP declines from 76 to 69 as positioning and embedded growth weaken the underrecognition assumption.',disposition:'ADVANCE'},lineage},
 VRT:{ticker:'VRT',verdict:'MATERIAL CHALLENGE — THESIS SURVIVES WITH CONDITIONS',
 challenged:'Thermal backlog may describe demand that cannot become installed capacity within the thesis horizon.',
 survived:'Higher compute density still requires thermal management; directional demand remains credible.',
 weakened:'The timing and cash-capture thesis materially weaken when qualified installation capacity is the bottleneck.',
 unresolved:'Whether commissioning capacity can expand before customers defer projects or working capital absorbs the benefit.',
 caseFor:['Thermal management is a necessary link in the infrastructure chain.','Backlog preserves evidence of customer intent.'],
 caseAgainst:['Backlog can grow precisely because commissioning is constrained.','Power access and installation delays can compound instead of diversifying away.'],
 challenges:[{title:'Backlog is not executable cash flow',why:'Growth is valuable only if installation and commissioning produce collectible revenue.',support:'Wash 2 already shows backlog growing faster than qualified installation capacity.',survived:'Directional thermal demand remains intact.',resolution:'Survives for review; withhold finalist eligibility until conversion uncertainty is resolved.'},{title:'A common timing bottleneck',why:'Cooling delivery and power energization must align within the same project.',support:'Installation capacity and power availability are shared constraints in the frozen state.',survived:'The need for cooling remains even if realization is delayed.',resolution:'Timing is uncertain independently of thesis direction.'}],
 alternative:{primary:'Backlog growth signals accelerating thermal demand.',alternative:'An installation bottleneck can accumulate backlog without improving near-term economic capture.',distinguish:'Completed installations and cash collection growing alongside backlog would distinguish executable demand from congestion.'},
 pricedIn:'The inherited moderate but rising burden anticipates growth while leaving conversion uncertain. Further backlog alone cannot justify stronger capture expectations.',
 timing:{direction:'Supported with conditions',state:'UNCERTAIN',reason:'Commissioning and grid availability can delay cash beyond the two-year thesis window even if thermal demand persists.'},
 integrity:{authority:'High',freshness:'Frozen demonstration snapshot',pointInTime:'T0–T2 retained; no later observations inserted',conflicts:{supporting:'Thermal backlog supports customer intent.',conflicting:'Qualified installation capacity limits realization of that same backlog.'},missing:'Commissioning throughput and cash-collection detail',reproducibility:'Deterministic fixture and preserved T0–T3 coordinates',confidence:'Moderate',limitation:'The demonstration cannot establish when constrained backlog converts into cash.',sufficient:true},
 comparative:{strength:'Direct thermal necessity',tradeoff:'Installation capacity and uncertain cash timing',conclusion:'A credible direction is insufficient for finalist selection while executable capture remains materially uncertain.',disagreement:'AR preserves directional demand but weakens capture; EI supports the existence of the constraint; SY withholds eligibility.'},
 status:'SURVIVES — REVIEW',causalIntact:true,t3:{t:3,ops:74,rap:49,why:'OPS falls from 81 to 74 because fewer orders are defensibly executable within the horizon. RAP falls from 64 to 49 as commissioning and power delays reinforce each other.',disposition:'REVIEW'},lineage},
 ETN:{ticker:'ETN',verdict:'CHALLENGE LARGELY ABSORBED',
 challenged:'Input inflation and utility-access delays could prevent electrical demand from turning into cash.',
 survived:'Varied electrical end uses and contract repricing preserve the causal path despite a near-term margin lag.',
 weakened:'Immediate recognition is not established; dormant participation may persist while projects await energization.',
 unresolved:'The duration of utility-access delays and the timing of investor recognition.',
 caseFor:['Diversified electrical end uses reduce reliance on one project schedule.','Repricing offers a documented fixture mechanism for absorbing input pressure.'],
 caseAgainst:['Shared power-access constraints can still delay multiple projects.','Dormant participation could signal delayed realization rather than an imminent recognition catalyst.'],
 challenges:[{title:'Input inflation versus repricing',why:'Revenue growth can coexist with weak cash capture if costs rise before prices adjust.',support:'The frozen state includes contract repricing lag and copper-related input pressure.',survived:'Multiple end uses and repricing mitigate, rather than remove, the margin threat.',resolution:'Challenge largely absorbed; retain the timing limitation.'},{title:'Dormant does not mean imminent',why:'Weak participation does not predict when recognition will begin.',support:'Wash 1 participation remains dormant despite strong Wash 2 causal durability.',survived:'Economic transmission does not require an immediate market response.',resolution:'Finalist eligibility survives without a recognition-date claim.'}],
 alternative:{primary:'Dormant participation leaves a potential recognition gap around electrical demand.',alternative:'Dormancy may rationally reflect slow utility access and delayed cash realization.',distinguish:'Energized projects and cash conversion preceding sustained participation would favor a delayed recognition opportunity.'},
 pricedIn:'The inherited moderate burden leaves room relative to the order runway, but it does not imply an inexpensive security or guarantee a rerating.',
 timing:{direction:'Supported',state:'EARLY',reason:'Repricing and energization can lag orders; direction is more defensible than the date of recognition.'},
 integrity:{authority:'High',freshness:'Frozen demonstration snapshot',pointInTime:'T0–T2 retained; no later observations inserted',conflicts:{supporting:'Varied electrical uses and repricing support durable transmission.',conflicting:'Dormant participation does not confirm when the economic case becomes recognized.'},missing:'Project-level energization dates',reproducibility:'Deterministic fixture and preserved T0–T3 coordinates',confidence:'High',limitation:'High confidence describes the internal demonstration evidence, not real-world source verification or a forecast.',sufficient:true},
 comparative:{strength:'Diversified end uses and repricing',tradeoff:'Slower realization and shared power access',conclusion:'A resilient economic path survives the cost challenge, with a slower recognition path still explicit.',disagreement:'AR absorbs much of the cost challenge; EI is High within the fixture; SY preserves early timing rather than treating confidence as speed.'},
 status:'FINALIST ELIGIBLE',causalIntact:true,t3:{t:3,ops:83,rap:75,why:'OPS stays 83 because electrical demand was already established. RAP improves from 72 to 75 as repricing survives the cost challenge; power access and recognition timing remain unresolved.',disposition:'ADVANCE'},lineage}
};
const sequence:[Wash3EventType,string][]=[
 ['WASH_3_STARTED','Beginning Wash 3 · frozen local demonstration'],
 ['ADVERSARIAL_REVIEW_STARTED','Constructing the strongest case against the surviving thesis'],
 ['ASSUMPTION_CHALLENGE_STARTED','Challenging causal and economic-capture assumptions'],
 ['ASSUMPTION_CHALLENGE_COMPLETE','Examining what may already be priced in'],
 ['CONTRADICTORY_EVIDENCE_REVIEW_STARTED','Searching the frozen demonstration evidence for contradictions'],
 ['CONTRADICTORY_EVIDENCE_REVIEW_COMPLETE','Preserving conflicts between demand and realization'],
 ['ALTERNATIVE_EXPLANATION_REVIEW_STARTED','Testing alternative explanations of participation and backlog'],
 ['ALTERNATIVE_EXPLANATION_REVIEW_COMPLETE','Challenging timing assumptions and shared dependencies'],
 ['ADVERSARIAL_REVIEW_COMPLETE','Separating what survived from what weakened'],
 ['EVIDENCE_INTEGRITY_REVIEW_STARTED','Testing evidence integrity and missing support'],
 ['EVIDENCE_INTEGRITY_REVIEW_COMPLETE','Keeping evidence confidence separate from thesis quality'],
 ['COMPARATIVE_SYNTHESIS_STARTED','Comparing surviving candidates across visible tradeoffs'],
 ['COMPARATIVE_SYNTHESIS_COMPLETE','Preserving unresolved analytical disagreement'],
 ['T3_STATE_FINALIZED','Finalizing T3 research state'],
 ['WASH_3_COMPLETE','Wash 3 complete · T3 established; finalist selection is yours']
];
export const wash3Events:ResearchActivityEvent[]=sequence.map(([type,message],sequence)=>({id:`wash3-${sequence}`,type,message,sequence,origin:'LOCAL_DEMO'}));
