import {useEffect,useState,type CSSProperties,type Dispatch} from 'react';
import type {CheckpointRun,CheckpointAction} from '../checkpoint/research';
import {finalistEligible,selectedFinalists} from './model';
import {wash3Events} from './fixtures';
import {CandidateDetail} from '../discovery/DiscoveryExperience';
import {Wash1Detail} from '../wash1/Wash1Detail';
import {Wash2Detail} from '../wash2/Wash2Detail';
import './wash3.css';
export function Wash3Experience({run,dispatch}:{run:CheckpointRun;dispatch:Dispatch<CheckpointAction>}){
 const w=run.wash3!;const complete=w.status==='COMPLETE';
 const [selected,select]=useState(w.participants[0]);const [challenge,setChallenge]=useState(0);const [detail,setDetail]=useState(false);
 const rows=w.participants.map(t=>w.results[t]).filter(Boolean);const r=w.results[selected];
 const old=run.wash1!.results[selected];const prior=w.prior.results[selected];
 const activity=run.activity.filter(e=>e.id.startsWith('wash3-'));
 function choose(t:string){select(t);setChallenge(0)}
 function finish(){for(let index=w.cursor;index<wash3Events.length;index++)dispatch({type:'WASH3_EVENT',index})}
 useEffect(()=>{if(complete)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){finish();return}const timer=window.setTimeout(()=>dispatch({type:'WASH3_EVENT',index:w.cursor}),240);return()=>clearTimeout(timer)},[w.cursor,complete,dispatch]);
 return <section className="wash-three wash-one" aria-label="Wash 3 research canvas">
 <p className="wash-note">Wash 2 state saved · {run.runId} · {w.participants.length} candidates proceeding to Wash 3</p>
 <span className="overline">{complete?'Wash 3 complete · T3':'Wash 3'} · local demonstration</span>
 <h2>Adversarial Confirmation</h2><p className="wash-question">Can the surviving thesis withstand the strongest credible challenge?</p>
 <section className={`activity-stream ${complete?'complete':''}`} aria-label="Wash 3 activity"><p role="status">{activity.at(-1)?.message??'Preparing the curated Wash 2 state'}</p>{!complete&&<button className="finish-discovery" onClick={finish}>Show complete Wash 3 demonstration</button>}<details><summary>{activity.length} Wash 3 activity events · review history</summary><ol>{activity.map(e=><li key={e.id}>{e.message}</li>)}</ol></details></section>
 {complete&&r&&<>
 <section className="adversarial-synthesis" aria-label="Adversarial synthesis"><h3>What remains after the strongest challenge?</h3><p>{rows.length} candidates challenged. {rows.filter(finalistEligible).length} eligible for your finalist selection; none selected automatically.</p><div className="survival-counts">{[...new Set(rows.map(c=>c.verdict))].map(v=><span key={v}><b>{rows.filter(c=>c.verdict===v).length}</b>{v}</span>)}</div><ul>{rows.map(c=><li key={c.ticker}><b>{c.ticker}</b> · {c.comparative.conclusion}</li>)}</ul><p className="wash-note">Frozen, invented demonstration evidence. Survival is not proof of investment success. No live research or calibrated probabilities.</p></section>
 <div className="adversarial-selector" role="group" aria-label="Select adversarial candidate">{rows.map(c=><button key={c.ticker} aria-label={`Select ${c.ticker} adversarial review`} aria-pressed={selected===c.ticker} onClick={()=>choose(c.ticker)}>{c.ticker}<small>{w.excluded.includes(c.ticker)?'USER EXCLUDED':c.status}</small></button>)}</div>
 <section className="adversarial-focus" aria-label="Adversarial Review"><span className="overline">{r.ticker} · AR-01</span><h3>{r.verdict}</h3><dl><dt>Original surviving thesis</dt><dd>{prior.reason}</dd><dt>What Fidelis attacked</dt><dd>{r.challenged}</dd><dt>What survived</dt><dd className="survived">{r.survived}</dd><dt>What weakened</dt><dd>{r.weakened}</dd><dt>What remains unresolved</dt><dd>{r.unresolved}</dd></dl></section>
 <section className="adversarial-cases" aria-label="Case For and Case Against"><div><h3>Case For</h3><ul>{r.caseFor.map(p=><li key={p}>{p}</li>)}</ul></div><div><h3>Case Against</h3><ul>{r.caseAgainst.map(p=><li key={p}>{p}</li>)}</ul></div></section>
 <section aria-label="Specific challenges"><h3>Inspect the challenge</h3><div className="challenge-selector">{r.challenges.map((c,i)=><button key={c.title} aria-label={`Inspect ${r.ticker} challenge ${i+1}: ${c.title}`} aria-pressed={i===challenge} onClick={()=>setChallenge(i)}>{c.title}</button>)}</div><div className="challenge-reading" aria-live="polite"><h4>{r.challenges[challenge].title}</h4><dl>{[['Why it matters',r.challenges[challenge].why],['Evidence supporting the challenge',r.challenges[challenge].support],['What survived',r.challenges[challenge].survived],['Resolution',r.challenges[challenge].resolution]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div></section>
 <section aria-label="Alternative Explanation"><h3>Could the same evidence mean something else?</h3><span className="overline">Alternative Explanation</span><dl><dt>Primary interpretation</dt><dd>{r.alternative.primary}</dd><dt>Alternative</dt><dd>{r.alternative.alternative}</dd><dt>What would distinguish them</dt><dd>{r.alternative.distinguish}</dd></dl></section>
 <section className="expectations-timing" aria-label="Expectations and timing"><div><h3>What may already be priced in?</h3><p className="wash-note">Inherited VE / Expectations · {old.ve.state} · {old.ve.momentum}</p><p>{r.pricedIn}</p><details><summary>Frozen expectations evidence</summary><p>{old.ve.evidence}</p><p>{old.ve.limitation}</p></details></div><div><h3>Timing is a separate challenge</h3><dl><dt>Thesis direction</dt><dd>{r.timing.direction}</dd><dt>Timing</dt><dd>{r.timing.state}</dd></dl><p>{r.timing.reason}</p></div></section>
 <section aria-label="Evidence Integrity"><span className="overline">{r.ticker} · EI-01</span><h3>Does the conclusion deserve its confidence?</h3><dl className="integrity-dimensions">{[['Authority',r.integrity.authority],['Freshness',r.integrity.freshness],['Point-in-time integrity',r.integrity.pointInTime],['Missing evidence',r.integrity.missing],['Reproducibility',r.integrity.reproducibility],['Overall confidence',r.integrity.confidence]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="wash-note">Evidence confidence: {r.integrity.confidence}. Thesis survival: {prior.survival}. Separate analytical facts; neither is a hidden score adjustment.</p><h4>Key limitation</h4><p>{r.integrity.limitation}</p><div className="evidence-conflict"><h4>Preserved evidence conflict</h4><dl><dt>Supporting evidence</dt><dd>{r.integrity.conflicts.supporting}</dd><dt>Conflicting evidence</dt><dd>{r.integrity.conflicts.conflicting}</dd></dl></div></section>
 <section aria-label="Comparative Synthesis"><span className="overline">SY-01 · surviving conclusions</span><h3>Which expression of the thesis survives most convincingly?</h3><p className="wash-note">Compare the tradeoffs. No new primary research and no opaque final score.</p><div className="tradeoff-list">{rows.map(c=><button key={c.ticker} aria-label={`Compare ${c.ticker} tradeoffs`} aria-pressed={selected===c.ticker} onClick={()=>choose(c.ticker)}><b>{c.ticker}<small>{w.excluded.includes(c.ticker)?'USER EXCLUDED':c.status}</small></b><span>Best: {c.comparative.strength}<small>Tradeoff: {c.comparative.tradeoff}</small></span></button>)}</div><dl className="integrity-dimensions">{[['Economic Reality',old.economic.state],['Market Recognition',old.recognition.state],['Causal strength',prior.ct.state],['Principal fragility',prior.fragilities[0].mechanism],['Adversarial survival',r.verdict],['Evidence confidence',r.integrity.confidence],['Expectations burden',old.ve.state],['Timing',r.timing.state]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h4>Preserved disagreement · {r.ticker}</h4><p>{r.comparative.disagreement}</p><p>{r.comparative.conclusion}</p></section>
 <section aria-label="T0 to T3 trajectories"><h3>What did adversarial review change?</h3><p className="wash-note">OPS / RAP are demonstration research coordinates, not calibrated forecasts. T3 accumulates the research; it is not a new final score.</p><div className="trajectory-grid">{rows.map(c=>{const points=run.universe[c.ticker].trajectory;const t2=w.prior.results[c.ticker].t2;return <button key={c.ticker} className={selected===c.ticker?'selected':''} aria-label={`Select ${c.ticker} T0 to T3 trajectory`} aria-pressed={selected===c.ticker} onClick={()=>choose(c.ticker)}><b>{c.ticker}</b><svg className="trajectory" viewBox="0 0 180 110" role="img" aria-label={`${c.ticker}: ${points.map(p=>`T${p.t} ${p.ops}/${p.rap}`).join(', ')} OPS/RAP`}><path className="trajectory-axes" d="M15 5V88H170"/><text x="1" y="10">RAP</text><text x="147" y="104">OPS</text><path className="prior-path" d={points.slice(0,3).map((p,i)=>`${i?'L':'M'}${15+p.ops*1.45} ${88-p.rap*.78}`).join('')}/><path className="movement-line" d={`M${15+t2.ops*1.45} ${88-t2.rap*.78}L${15+c.t3.ops*1.45} ${88-c.t3.rap*.78}`}/>{points.map(p=><circle key={p.t} className={p.t===3?'point-t1':'point-t0'} cx={15+p.ops*1.45} cy={88-p.rap*.78} r={p.t===3?4:3} style={p.t===3?{'--dx':`${(t2.ops-p.ops)*1.45}px`,'--dy':`${(p.rap-t2.rap)*.78}px`} as CSSProperties:undefined}/>)}</svg><span>{points.map(p=>`T${p.t} ${p.ops}/${p.rap}`).join(' → ')}</span></button>})}</div><div className="movement-explanation"><span className="overline">{r.ticker} · T2 → T3</span><p>{r.t3.why}</p><details><summary>Complete trajectory story · T0 → T1 → T2 → T3</summary>{run.universe[selected].trajectory.map(p=><p key={p.t}><b>T{p.t} · {p.ops} OPS / {p.rap} RAP</b><br/>{p.why}</p>)}</details></div><button className="wash-inspect-button" onClick={()=>setDetail(true)}>Inspect {selected} · complete research history</button></section>
 <section aria-label="Final survivor selection"><h3>The survivors. Your finalists.</h3><p className="wash-note">Eligibility is a research state. Selection is your decision. Held, failed and excluded candidates retain their history.</p>{rows.map(c=><div className="final-survivor" key={c.ticker}><button className="survivor-summary" aria-label={`Inspect ${c.ticker} final survivor`} aria-pressed={selected===c.ticker} onClick={()=>choose(c.ticker)}><b>{c.ticker} · {w.excluded.includes(c.ticker)?'USER EXCLUDED':c.status}</b><span>{c.verdict}</span><small>Thesis: {w.prior.results[c.ticker].survival} · Evidence: {c.integrity.confidence}</small><span>Strength: {c.comparative.strength}</span><span>Challenge: {c.comparative.tradeoff}</span><small>Timing: {c.timing.state} · T3: {c.t3.ops} OPS / {c.t3.rap} RAP</small></button><div className="finalist-controls"><label><input type="checkbox" aria-label={`Select ${c.ticker} for Expression`} checked={selectedFinalists(w).includes(c.ticker)} disabled={!finalistEligible(c)||w.excluded.includes(c.ticker)} onChange={()=>dispatch({type:'SELECT_FINALIST',ticker:c.ticker})}/>Select for Expression</label><button onClick={()=>dispatch({type:'CURATE_WASH3',ticker:c.ticker})} aria-label={`${w.excluded.includes(c.ticker)?'Re-include':'Exclude'} ${c.ticker} from Wash 3`}>{w.excluded.includes(c.ticker)?'Re-include':'Exclude'}</button></div>{!finalistEligible(c)&&<p className="wash-note">Not eligible · {c.comparative.conclusion}</p>}</div>)}<details><summary>Wash 3 user decisions · {w.decisions.length}</summary>{w.decisions.map(d=><p key={d.ordinal}>{d.ticker} · {d.decision}</p>)}</details></section>
 <div className="expression-firewall"><p>Expression can change how a surviving thesis is owned. It cannot repair thesis failure, insufficient evidence or broken causal transmission.</p><p className="wash-note">No investment recommendation or option structure is provided.</p></div><div className="discovery-proceed"><span>{selectedFinalists(w).length} finalists selected</span><button disabled={!selectedFinalists(w).length} onClick={()=>dispatch({type:'SAVE_FINALISTS'})}>Proceed to Expression · {selectedFinalists(w).length} selected</button>{w.finalistsSaved&&<p role="status">Finalists saved. Expression begins in the next approved checkpoint.</p>}</div>
 </>}
 {detail&&r&&<CandidateDetail entry={run.wash1!.discovery[selected]} discovery={run.discovery!} close={()=>setDetail(false)} compactHistory><details><summary>Wash 1 · Reality & Recognition</summary><Wash1Detail r={old}/></details><Wash2Detail r={prior}/><section className="wash-three"><h3>Wash 3 · Adversarial Confirmation · T3</h3><p>{r.verdict}</p><p>{r.challenged}</p><p>Survived: {r.survived}</p><p>Weakened: {r.weakened}</p><p>Unresolved: {r.unresolved}</p><p>{r.t3.why}</p><p>Evidence confidence: {r.integrity.confidence} · {r.integrity.limitation}</p><p>Lineage: {r.lineage.fixtureVersion} · {r.lineage.prior} · local demonstration</p><details><summary>Complete user decision history</summary>{run.discovery!.decisions.filter(d=>d.ticker===selected).map(d=><p key={`d${d.ordinal}`}>Discovery · {d.decision}</p>)}{run.exclusions.filter(d=>d.ticker===selected).map(d=><p key={d.event}>{d.stage} · {d.decision}</p>)}{w.decisions.filter(d=>d.ticker===selected).map(d=><p key={`w${d.ordinal}`}>Wash 3 · {d.decision}</p>)}</details></section></CandidateDetail>}
 </section>
}
