import {Wash1Detail} from '../wash1/Wash1Detail';
import {useEffect,useState,type Dispatch,type ReactNode} from 'react';
import type {CheckpointRun,CheckpointAction} from '../checkpoint/research';
import {discoveryEvents} from './fixtures';
import {discoveryCounts,type CandidateDiscoveryState,type DiscoveryResult} from './model';
import './discovery.css';
export function CandidateDetail({entry,discovery,close,children}:{entry:CandidateDiscoveryState;discovery:DiscoveryResult;close:()=>void;children?:ReactNode}){
 const c=entry.candidate;const path=discovery.pathways.find(p=>p.id===c.pathway);
 useEffect(()=>{const el=document.getElementById('discovery-detail') as HTMLDialogElement;el.showModal();return()=>el.close()},[]);
 return <dialog id="discovery-detail" className="discovery-detail" aria-label={`${c.ticker} Discovery detail`} onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><button className="detail-close" onClick={close} autoFocus aria-label="Close candidate detail">×</button><span className="overline">Demonstration · relevance only</span><h2>{c.ticker}</h2><p className="detail-company">{c.company}</p><dl><dt>Discovered through</dt><dd>AI infrastructure capex → data-center buildout → {path?.label}</dd><dt>Thesis relationship</dt><dd>{c.relationship}</dd><dt>Exposure validation</dt><dd>{entry.validation==='PENDING'?'Unresolved — validation pending':c.exposure}</dd><dt>Evidence confidence</dt><dd>{c.confidence} · sanitized illustrative evidence</dd>{!children&&<><dt>Economic reality</dt><dd>Not yet evaluated</dd><dt>Market recognition</dt><dd>Not yet evaluated</dd></>}<dt>Discovery state</dt><dd>{entry.validation} · {entry.userState==='USER_EXCLUDED'?'Excluded by you':'No user exclusion'}</dd></dl>{c.rejection&&entry.validation==='REJECTED'&&<p className="rejection-reason">{c.rejection}</p>}{c.recall&&<p className="recall-note">Discovery Recall challenged the first-pass set and added this execution pathway. No live search was performed.</p>}<details><summary>Decision history</summary>{discovery.decisions.filter(e=>e.ticker===c.ticker).map(e=><p key={e.ordinal}>{e.decision==='USER_EXCLUDED'?'Excluded by you':'Re-included by you'}</p>)}{!discovery.decisions.some(e=>e.ticker===c.ticker)&&<p>No user decisions recorded.</p>}</details>{children}<p className="discovery-muted">Discovery establishes relevance, not investment merit. These are prepared demonstration findings, not current company research.</p></dialog>
}
function DiscoveryMap({discovery,selected,hover,setHover,inspect}:{discovery:DiscoveryResult;selected:string|null;hover:string|null;setHover:(id:string|null)=>void;inspect:(id:string)=>void}){
 const active=hover??selected;const candidate=active?discovery.candidates[active]:null;
 return <section className="discovery-map" aria-label="Thesis causal map"><div className="causal-trunk"><span className="overline">Your thesis → economic pathways</span><h3>AI infrastructure capex</h3><span className="trunk-connector" aria-hidden="true"/><p>Data-center buildout</p></div><div className="discovery-branches">{discovery.pathways.map(path=><section key={path.id} className={`discovery-branch ${candidate?.candidate.pathway===path.id?'path-active':''}`} aria-label={path.label}><h4>{path.label}</h4><p className="branch-relation">{path.relationship.explanation}</p><div className="branch-candidates">{Object.values(discovery.candidates).filter(c=>c.candidate.pathway===path.id).map(entry=><button key={entry.candidate.ticker} aria-label={`Inspect ${entry.candidate.ticker} on ${path.label} pathway`} className={`${active===entry.candidate.ticker?'candidate-active':''} ${entry.userState==='USER_EXCLUDED'?'user-excluded':''} ${entry.validation==='REJECTED'?'not-relevant':''}`} onMouseEnter={()=>setHover(entry.candidate.ticker)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(entry.candidate.ticker)} onBlur={()=>setHover(null)} onClick={()=>inspect(entry.candidate.ticker)}>{entry.candidate.ticker}{entry.candidate.recall&&<small>Recall</small>}{entry.userState==='USER_EXCLUDED'&&<small>Excluded</small>}{entry.validation==='REJECTED'&&<small>Not validated</small>}</button>)}</div></section>)}</div><div className="map-context" aria-live="polite">{candidate?<><b>{candidate.candidate.ticker} · {candidate.candidate.company}</b><p>{candidate.candidate.relationship}</p></>:<p>Hover, focus or select a candidate to follow its causal path. This map is specific to the demonstration thesis, not a permanent taxonomy.</p>}</div></section>
}
export function DiscoveryExperience({run,dispatch}:{run:CheckpointRun;dispatch:Dispatch<CheckpointAction>}){
 const d=run.discovery!;const complete=d.status==='COMPLETE';const count=discoveryCounts(d);const [selected,select]=useState<string|null>(null);const [detail,setDetail]=useState<string|null>(null);const [hover,setHover]=useState<string|null>(null);
 function finish(){for(const event of discoveryEvents.slice(d.cursor))dispatch({type:'DISCOVERY_EVENT',event})}
 useEffect(()=>{if(complete)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){for(const event of discoveryEvents.slice(d.cursor))dispatch({type:'DISCOVERY_EVENT',event});return}const next=discoveryEvents[d.cursor];if(!next)return;const timer=window.setTimeout(()=>dispatch({type:'DISCOVERY_EVENT',event:next}),380);return()=>clearTimeout(timer)},[d.cursor,complete,dispatch]);
 const inspect=(id:string)=>{select(id);setDetail(id)};const events=run.activity.filter(e=>e.id.startsWith('discovery-'));const latest=events.at(-1);
 const rows=Object.values(d.candidates);const retained=rows.filter(c=>c.validation!=='REJECTED'&&c.userState==='RETAINED');const excluded=rows.filter(c=>c.userState==='USER_EXCLUDED');const rejected=rows.filter(c=>c.validation==='REJECTED');
 function row(entry:CandidateDiscoveryState){const c=entry.candidate;return <div key={c.ticker} className={`discovery-row ${selected===c.ticker?'selected':''}`}><button className="discovery-row-select" onClick={()=>inspect(c.ticker)} aria-label={`Inspect ${c.ticker} ${c.company}`}><b>{c.ticker}<span>{c.company}</span></b><span>{d.pathways.find(p=>p.id===c.pathway)?.label}{c.recall?' · Recall':''}<small>Exposure: {entry.validation==='PENDING'?'Unresolved':c.exposure} · Evidence: {c.confidence}</small></span><small>{entry.validation==='PENDING'?'Pending validation':entry.userState==='USER_EXCLUDED'?'Excluded by you':'Validated relevance'}</small></button>{complete&&!run.wash1&&entry.validation==='VALIDATED'&&<button className="curation-control" onClick={()=>dispatch({type:'CURATE_DISCOVERY',ticker:c.ticker})} aria-label={`${entry.userState==='USER_EXCLUDED'?'Re-include':'Exclude'} ${c.ticker}`}>{entry.userState==='USER_EXCLUDED'?'Re-include':'Exclude'}</button>}</div>}
 return <section className="discovery-experience" aria-label="Discovery research canvas"><details className="locked-discovery-thesis"><summary>Locked thesis · retained as the research anchor</summary><p>{run.lockedThesis?.proposition}</p></details>
 {complete&&!run.wash1&&<div className="discovery-proceed"><span aria-live="polite"><b>{count.proceed}</b> candidates will proceed</span><button disabled={!count.proceed} onClick={()=>dispatch({type:'START_WASH1'})}>Proceed to Wash 1 <span aria-hidden="true">→</span></button>{d.readyToSave&&<p role="status">Discovery state ready to save. Wash 1 begins in the next approved checkpoint. This run is local; no backend save has occurred.</p>}</div>}
 <div className="discovery-heading"><div><span className="overline">{complete?'Discovery complete':'Discovery'} · local demonstration</span><h2>{complete?'Relevance, before merit.':'Following the causal thread.'}</h2></div>{!complete&&<button className="finish-discovery" onClick={finish}>Show complete demonstration</button>}</div>
 <section className={`activity-stream ${complete?'complete':''}`} aria-label="Discovery activity"><p className="active-operation" role="status">{latest?.message??'Preparing the locked thesis for Discovery'}</p><details><summary>{events.length} completed activity events · review history</summary><ol>{events.map(e=><li key={e.id}>{e.message}</li>)}</ol></details></section>
 {d.pathways.length>0&&<DiscoveryMap discovery={d} selected={selected} hover={hover} setHover={setHover} inspect={inspect}/>}
 {rows.length>0&&<section className="candidate-curation" aria-label="Candidate curation"><div className="curation-heading"><h3>{complete?'Your candidate universe':'Candidate exposures emerging'}</h3><span>{count.examined} considered</span></div>{complete&&<p className="discovery-summary">{count.examined} examined · {count.validated} validated, including {count.recall} through Recall · {count.rejected} rejected · {count.pending} unresolved</p>}<p className="discovery-muted">Economic reality and market recognition: <b>Not yet evaluated.</b> Exclusions are your decisions and never erase Discovery history.</p><div className="discovery-list" tabIndex={0} aria-label="Candidate list">{retained.map(row)}</div>{excluded.length>0&&<section className="excluded-candidates" aria-label="Excluded by you"><h4>Excluded by you</h4>{excluded.map(row)}</section>}{rejected.length>0&&<details className="rejected-candidates"><summary>{rejected.length} candidates not sufficiently relevant to this thesis</summary>{rejected.map(entry=><div key={entry.candidate.ticker}><button onClick={()=>inspect(entry.candidate.ticker)}>Inspect {entry.candidate.ticker}</button><p>{entry.candidate.rejection}</p></div>)}</details>}</section>}
 {complete&&<section className="discovery-insights" aria-label="Discovery insights"><div><span className="overline">Second-order exposure</span><p>Validated exposures extend beyond compute into networking, cooling, electrical infrastructure and manufacturing equipment.</p></div><div><span className="overline">Shared dependency</span><p>Different suppliers still depend on the same data-center investment transmission path. Relevance is not diversification.</p></div><div><span className="overline">Discovery Recall</span><p>Fidelis identified {count.recall} additional candidate whose illustrative exposure challenges the initial universe. Physical installation extends the electrical-infrastructure branch.</p></div><p className="discovery-muted">Prepared fixture findings only. No AI, external search, market data or evidence acquisition was performed.</p></section>}
 {detail&&d.candidates[detail]&&<CandidateDetail entry={d.candidates[detail]} discovery={d} close={()=>setDetail(null)}>{run.wash1?.results[detail]&&<Wash1Detail r={run.wash1.results[detail]}/>}</CandidateDetail>}
 </section>
}
