import {Wash2Detail} from '../wash2/Wash2Detail';
import {Wash1Detail} from '../wash1/Wash1Detail';
import {useEffect,useState,type Dispatch,type ReactNode} from 'react';
import type {CheckpointRun,CheckpointAction} from '../checkpoint/research';
import {discoveryEvents} from './fixtures';
import {discoveryCounts,type CandidateDiscoveryState,type DiscoveryResult} from './model';
import './discovery.css';
import {opportunity,demoReturns,returnProvenance} from './opportunity';
function DiscoveryHistory({compact,children}:{compact:boolean;children:ReactNode}){return compact?<details><summary>Discovery · exposure & lineage</summary>{children}</details>:<>{children}</>}
export function CandidateDetail({entry,discovery,close,children,compactHistory=false}:{entry:CandidateDiscoveryState;discovery:DiscoveryResult;close:()=>void;children?:ReactNode;compactHistory?:boolean}){
 const c=entry.candidate;const path=discovery.pathways.find(p=>p.id===c.pathway);
 useEffect(()=>{const el=document.getElementById('discovery-detail') as HTMLDialogElement;el.showModal();return()=>el.close()},[]);
 return <dialog id="discovery-detail" className="discovery-detail" aria-label={`${c.ticker} Discovery detail`} onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><button className="detail-close" onClick={close} autoFocus aria-label="Close candidate detail">×</button><span className="overline">{compactHistory?'Demonstration · research history':'Demonstration · relevance only'}</span><h2>{c.ticker}</h2><p className="detail-company">{c.company}</p><DiscoveryHistory compact={compactHistory}><dl><dt>Discovered through</dt><dd>AI infrastructure capex → data-center buildout → {path?.label}</dd><dt>Thesis relationship</dt><dd>{c.relationship}</dd><dt>Exposure validation</dt><dd>{entry.validation==='PENDING'?'Unresolved — validation pending':c.exposure}</dd><dt>Evidence confidence</dt><dd>{c.confidence} · sanitized illustrative evidence</dd>{!children&&<><dt>Economic reality</dt><dd>Not yet evaluated</dd><dt>Market recognition</dt><dd>Not yet evaluated</dd></>}<dt>Discovery state</dt><dd>{entry.validation} · {entry.userState==='USER_EXCLUDED'?'Excluded by you':'No user exclusion'}</dd></dl>{c.rejection&&entry.validation==='REJECTED'&&<p className="rejection-reason">{c.rejection}</p>}{c.recall&&<p className="recall-note">Discovery Recall challenged the first-pass set and added this execution pathway. No live search was performed.</p>}<details><summary>Decision history</summary>{discovery.decisions.filter(e=>e.ticker===c.ticker).map(e=><p key={e.ordinal}>{e.decision==='USER_EXCLUDED'?'Excluded by you':'Re-included by you'}</p>)}{!discovery.decisions.some(e=>e.ticker===c.ticker)&&<p>No user decisions recorded.</p>}</details></DiscoveryHistory>{children}<p className="discovery-muted">Discovery establishes relevance, not investment merit. These are prepared demonstration findings, not current company research.</p></dialog>
}
function DiscoveryMap({discovery,selected,hover,setHover,inspect}:{discovery:DiscoveryResult;selected:string|null;hover:string|null;setHover:(id:string|null)=>void;inspect:(id:string)=>void}){
 const active=hover??selected;const candidate=active?discovery.candidates[active]:null;
 return <section className="discovery-map" aria-label="Thesis causal map"><div className="causal-trunk"><span className="overline">Your thesis → economic pathways</span><h3>AI infrastructure capex</h3><span className="trunk-connector" aria-hidden="true"/><p>Data-center buildout</p></div><div className="discovery-branches">{discovery.pathways.map(path=><section key={path.id} className={`discovery-branch ${candidate?.candidate.pathway===path.id?'path-active':''}`} aria-label={path.label}><h4>{path.label}</h4><p className="branch-relation">{path.relationship.explanation}</p><div className="branch-candidates">{Object.values(discovery.candidates).filter(c=>c.candidate.pathway===path.id).map(entry=><button key={entry.candidate.ticker} aria-label={`Inspect ${entry.candidate.ticker} on ${path.label} pathway`} className={`${active===entry.candidate.ticker?'candidate-active':''} ${entry.userState==='USER_EXCLUDED'?'user-excluded':''} ${entry.validation==='REJECTED'?'not-relevant':''}`} onMouseEnter={()=>setHover(entry.candidate.ticker)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(entry.candidate.ticker)} onBlur={()=>setHover(null)} onClick={()=>inspect(entry.candidate.ticker)}>{entry.candidate.ticker}{entry.candidate.recall&&<small>Recall</small>}{entry.userState==='USER_EXCLUDED'&&<small>Excluded</small>}{entry.validation==='REJECTED'&&<small>Not validated</small>}</button>)}</div></section>)}</div><div className="map-context" aria-live="polite">{candidate?<><b>{candidate.candidate.ticker} · {candidate.candidate.company}</b><p>{candidate.candidate.relationship}</p></>:<p>Hover, focus or select a candidate to follow its causal path. This map is specific to the demonstration thesis, not a permanent taxonomy.</p>}</div></section>
}
function OneMonthReturn({ticker}:{ticker:string}){
 const value=demoReturns[ticker];const available=value!==undefined;
 return <details className={`one-month-return ${!available||value===0?'neutral':value>0?'positive':'negative'}`}><summary aria-label={`${ticker} 1M return details`}><span className="return-label">1M return · demo</span>{available?`${value>0?'↑ +':value<0?'↓ −':'— '}${Math.abs(value).toFixed(1)}%`:'Unavailable'}</summary><div className="return-provenance">{available?<><b>Illustrative only · not verified market data</b><p>{returnProvenance.kind}</p><p>Measurement: {returnProvenance.start} → {returnProvenance.end}<br/>As of: {returnProvenance.asOf}</p><p>Source: {returnProvenance.source}. Invented values for interface review.</p></>:<p>No supported demonstration return is available.</p>}<p>Display only. Does not affect relevance, selection or confidence.</p></div></details>
}
function UserAdditions({d,dispatch,frozen}:{d:DiscoveryResult;dispatch:Dispatch<CheckpointAction>;frozen:boolean}){
 const [ticker,setTicker]=useState('');const [rationale,setRationale]=useState('');const [notice,setNotice]=useState('');
 const entries=Object.values(d.userAdditions??{}).filter(e=>!e.removed);
 return <section className="user-additions" aria-label="Your candidate additions"><h4>Add a candidate</h4><p className="discovery-muted">Bring an overlooked company into consideration. Supported demo candidates retain the same assessment; other tickers stay pending and cannot enter a wash.</p>{!frozen&&<form onSubmit={e=>{e.preventDefault();const t=ticker.trim().toUpperCase();if(!/^[A-Z][A-Z0-9.-]{0,9}$/.test(t)){setNotice('Enter a valid ticker, up to 10 characters.');return}if(d.userAdditions?.[t]&&!d.userAdditions[t].removed){setNotice(`${t} is already in your additions.`);return}dispatch({type:'ADD_DISCOVERY_CANDIDATE',ticker:t,rationale});setTicker('');setRationale('');setNotice(`${t} added by you. ${d.candidates[t]?'Existing demo assessment retained; universe is not duplicated.':'Pending assessment; unavailable for washes.'}`)}}><label>Ticker<input value={ticker} maxLength={10} onChange={e=>setTicker(e.target.value)} placeholder="e.g. ANET" autoCapitalize="characters"/></label><label className="addition-rationale">Rationale <span>(optional)</span><input value={rationale} maxLength={500} onChange={e=>setRationale(e.target.value)} placeholder="Why might this company benefit?"/></label><button type="submit" disabled={!ticker.trim()}>Add candidate</button></form>}<p className="addition-notice" aria-live="polite">{notice}</p>{entries.map(e=><article key={e.ticker} className="user-added-candidate"><div><b>{e.ticker}</b> <small>Added by you · user suggestion</small><p>{e.rationale||'No rationale supplied.'}</p><p>{d.candidates[e.ticker]?`Existing demonstration assessment: ${d.candidates[e.ticker].validation}. Same evidence and criteria; your addition does not override exclusion or duplicate the universe.`:'Pending assessment · identity, thesis relevance and opportunity are unverified. Not eligible for downstream washes.'}</p></div><OneMonthReturn ticker={e.ticker}/>{!frozen&&<button onClick={()=>dispatch({type:'REMOVE_DISCOVERY_ADDITION',ticker:e.ticker})} aria-label={`Remove addition ${e.ticker}`}>Remove addition</button>}</article>)}{Object.values(d.userAdditions??{}).some(e=>e.removed)&&<section className="removed-additions" aria-label="Removed suggestions"><h4>Removed suggestions</h4>{Object.values(d.userAdditions??{}).filter(e=>e.removed).map(e=><div key={e.ticker}><span>{e.ticker} · removed by you</span>{!frozen&&<button onClick={()=>dispatch({type:'ADD_DISCOVERY_CANDIDATE',ticker:e.ticker,rationale:e.rationale})}>Restore addition {e.ticker}</button>}</div>)}</section>}{(d.additionHistory?.length??0)>0&&<details><summary>User addition history · {d.additionHistory!.length} events</summary><ol>{d.additionHistory!.map(e=><li key={e.ordinal}>{e.ticker} · {e.action==='ADDED'?'Added by you':'Addition removed'}{e.rationale?` · ${e.rationale}`:''}</li>)}</ol><p>Removing a suggestion preserves this history and does not exclude an already discovered candidate.</p></details>}</section>
}
export function DiscoveryExperience({run,dispatch}:{run:CheckpointRun;dispatch:Dispatch<CheckpointAction>}){
 const d=run.discovery!;const complete=d.status==='COMPLETE';const count=discoveryCounts(d);const [selected,select]=useState<string|null>(null);const [detail,setDetail]=useState<string|null>(null);const [hover,setHover]=useState<string|null>(null);
 function finish(){for(const event of discoveryEvents.slice(d.cursor))dispatch({type:'DISCOVERY_EVENT',event})}
 useEffect(()=>{if(complete)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){for(const event of discoveryEvents.slice(d.cursor))dispatch({type:'DISCOVERY_EVENT',event});return}const next=discoveryEvents[d.cursor];if(!next)return;const timer=window.setTimeout(()=>dispatch({type:'DISCOVERY_EVENT',event:next}),380);return()=>clearTimeout(timer)},[d.cursor,complete,dispatch]);
 const inspect=(id:string)=>{select(id);setDetail(id)};const events=run.activity.filter(e=>e.id.startsWith('discovery-'));const latest=events.at(-1);
 const rows=Object.values(d.candidates);const retained=rows.filter(c=>c.validation!=='REJECTED'&&c.userState==='RETAINED');const excluded=rows.filter(c=>c.userState==='USER_EXCLUDED');const rejected=rows.filter(c=>c.validation==='REJECTED');
 function row(entry:CandidateDiscoveryState){const c=entry.candidate;const hypothesis=opportunity[c.ticker];return <article key={c.ticker} className={`discovery-row ${selected===c.ticker?'selected':''}`} aria-label={`${c.ticker} candidate`}>
 <div className="candidate-card-heading"><div><button className="discovery-row-select" onClick={()=>inspect(c.ticker)} aria-label={`Inspect ${c.ticker} ${c.company}`}><b>{c.ticker}</b></button><p className="candidate-company">{c.company}</p></div>{complete&&!run.wash1&&entry.validation==='VALIDATED'&&<button className="curation-control" onClick={()=>dispatch({type:'CURATE_DISCOVERY',ticker:c.ticker})} aria-label={`${entry.userState==='USER_EXCLUDED'?'Re-include':'Exclude'} ${c.ticker}`}>{entry.userState==='USER_EXCLUDED'?'Re-include':'Exclude'}</button>}</div>
 <details className="candidate-reasoning"><summary aria-label={`${c.ticker} thesis connection, opportunity and tests`}>Thesis connection · opportunity · needs testing</summary><dl><dt>Thesis connection</dt><dd>{c.relationship}</dd>{hypothesis&&<><dt>Opportunity hypothesis</dt><dd>{hypothesis.potential}</dd><dt>Needs testing</dt><dd>{hypothesis.test}</dd></>}{c.rejection&&<><dt>Not validated</dt><dd>{c.rejection}</dd></>}</dl></details>
 <div className="candidate-metrics"><div><span className="metric-label">Category{c.recall?' · Recall':''}</span><strong>{d.pathways.find(p=>p.id===c.pathway)?.label}</strong></div><div><span className="metric-label">Exposure</span><strong>{entry.validation==='PENDING'?'Unresolved':c.exposure}</strong></div><OneMonthReturn ticker={c.ticker}/></div><div className="candidate-state"><span>Evidence confidence: {c.confidence}</span><span>{entry.validation==='PENDING'?'Pending validation':entry.validation==='REJECTED'?'Analytical rejection':entry.userState==='USER_EXCLUDED'?'Excluded by you':'Validated relevance · opportunity untested'}</span></div></article>}
 return <section className="discovery-experience" aria-label="Discovery research canvas">
 <section className={`activity-stream ${complete?'complete':''}`} aria-label="Discovery activity"><h2 className="discovery-quote" aria-label="Relevance before merit"><span>Relevance before</span><span>Merit</span></h2><div className="activity-information"><div className="activity-heading"><span className="processing-label">{complete?'Discovery complete':'Discovery processing'}</span><small>Local demonstration</small></div><p className="active-operation" role="status">{latest?.message??'Preparing the locked thesis for Discovery'}</p><details><summary>{events.length} completed activity events · review history</summary><ol>{events.map(e=><li key={e.id}>{e.message}</li>)}</ol></details>{!complete&&<button className="finish-discovery" onClick={finish}>Show complete demonstration</button>}</div></section>
 <section className="candidate-curation" aria-label="Candidate curation"><div className="curation-heading"><h3>YOUR CANDIDATE UNIVERSE</h3><span>{count.examined} considered</span></div><p className="discovery-intent">Discovery looks for thesis relevance and preliminary financial-opportunity potential. These are hypotheses to investigate—not return forecasts. The washes test economic reality, recognition and thesis survival.</p>{complete&&<p className="discovery-summary">{count.examined} examined · {count.validated} validated, including {count.recall} through Recall · {count.rejected} rejected · {count.pending} unresolved</p>}<p className="discovery-muted">Evidence confidence describes support for the exposure, separately from potential upside. All findings and 1M returns are illustrative demo fixtures. No live research or market data.</p><div className="discovery-list" aria-label="Candidate list">{retained.map(row)}{rows.length===0&&<p className="discovery-muted">Candidates will appear as the demonstration progresses.</p>}</div>{excluded.length>0&&<section className="excluded-candidates" aria-label="Excluded by you"><h4>Excluded by you</h4>{excluded.map(row)}</section>}{rejected.length>0&&<details className="rejected-candidates"><summary>{rejected.length} candidates not sufficiently relevant to this thesis</summary>{rejected.map(row)}</details>}{complete&&<UserAdditions d={d} dispatch={dispatch} frozen={!!run.wash1}/>}</section>
 {complete&&!run.wash1&&<div className="discovery-proceed"><div><span aria-live="polite"><b>{count.proceed}</b> candidates will proceed</span><p>Wash 1 · Reality & Recognition tests whether demand becomes economic value and what the market may already recognize.</p></div><button disabled={!count.proceed} onClick={()=>dispatch({type:'START_WASH1'})}>Proceed to Wash 1 <span aria-hidden="true">→</span></button></div>}
 {d.pathways.length>0&&<><div className="pathway-heading"><h3>How the thesis connects</h3><p className="discovery-muted">Trace the same candidates through their causal pathways. Exclusions remain in history.</p></div><DiscoveryMap discovery={d} selected={selected} hover={hover} setHover={setHover} inspect={inspect}/></>}
 {complete&&<section className="discovery-insights" aria-label="Discovery insights"><div><span className="overline">Second-order exposure</span><p>Validated exposures extend beyond compute into networking, cooling, electrical infrastructure and manufacturing equipment.</p></div><div><span className="overline">Shared dependency</span><p>Different suppliers still depend on the same data-center investment transmission path. Relevance is not diversification.</p></div><div><span className="overline">Discovery Recall</span><p>Recall added {count.recall} candidate to challenge the first-pass set. Physical installation extends the electrical-infrastructure branch.</p></div><p className="discovery-muted">Prepared fixture findings only. No AI, external search, market data or evidence acquisition was performed.</p></section>}
 {detail&&d.candidates[detail]&&<CandidateDetail entry={d.candidates[detail]} discovery={d} close={()=>setDetail(null)} compactHistory={!!run.wash2?.results[detail]}>{run.wash1?.results[detail]&&(run.wash2?.results[detail]?<><details><summary>Wash 1 · Reality & Recognition</summary><Wash1Detail r={run.wash1.results[detail]}/></details><Wash2Detail r={run.wash2.results[detail]}/></>:<Wash1Detail r={run.wash1.results[detail]}/>)}</CandidateDetail>}
 </section>
}
