import {useRef,type Dispatch} from 'react';
import type {CheckpointRun,CheckpointAction} from '../checkpoint/research';
import {expressionFamilies,expressionIntents} from './model';
import {familyNames,intentNames,expressionLimitation} from './fixtures';
import './expression.css';
export function ExpressionExperience({run,dispatch}:{run:CheckpointRun;dispatch:Dispatch<CheckpointAction>}){
 const e=run.expression!;const f=e.finalists[e.active];const c=f.context;const a=f.analysis;
 const inspected=a?.comparisons.find(x=>x.family===f.inspected);
 const composing=useRef(false);const composer=useRef<HTMLTextAreaElement>(null);
 const send=()=>{if(!f.draft.trim()||composing.current)return;dispatch({type:'EXPRESSION_REPLY',ticker:e.active,text:f.draft});composer.current?.focus({preventScroll:true})};
 return <section className="expression-stage" aria-label="Expression canvas">
  <p className="wash-note">Finalists saved · {run.runId} · {e.participants.length} candidates selected for Expression</p>
  <span className="overline">{e.status==='COMPLETE'?'Expression complete':'Expression'} · local demonstration</span>
  <h2>How should the surviving thesis be expressed?</h2>
  <p className="expression-intro">Research established what survived. Now compare how to own it—without changing that research.</p>
  <div className="expression-finalists" role="group" aria-label="Expression finalists">{e.participants.map(t=><button key={t} aria-label={`View ${t} Expression`} aria-pressed={e.active===t} onClick={()=>dispatch({type:'SWITCH_EXPRESSION_FINALIST',ticker:t})}>{t}<small>{e.finalists[t].confirmed?'Confirmed':e.finalists[t].analysis?'Comparison ready':'Your preference'}</small></button>)}</div>
  <section aria-label="Inherited research context" className="expression-context">
   <h3>{c.ticker} · {c.company}</h3>
   <dl className="expression-facts">{[['Thesis horizon',c.horizon],['Recognition',c.t1.recognition.state],['Timing',c.t3.timing.state],['Evidence confidence',c.t3.integrity.confidence]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
   <p>{c.t3.survived}</p><p className="wash-note">Principal challenge: {c.t3.comparative.tradeoff}</p>
   <details><summary>Inspect the research we carry forward</summary><dl><dt>Locked thesis</dt><dd>{c.thesis}</dd><dt>Economic Reality</dt><dd>{c.t1.economic.state} · {c.t1.economic.momentum}</dd><dt>Expectations burden</dt><dd>{c.t1.ve.state} · {c.t3.pricedIn}</dd><dt>Adversarial verdict</dt><dd>{c.t3.verdict}</dd><dt>Timing / recognition clock</dt><dd>{c.t3.timing.reason}</dd><dt>Principal fragility</dt><dd>{c.t2.fragilities[0].effect}</dd><dt>T0 → T3 · demonstration OPS / RAP</dt><dd>{c.trajectory.map(p=>`T${p.t} ${p.ops}/${p.rap}`).join(' → ')}</dd><dt>Lineage</dt><dd>{c.lineage.runId} · saved T3 · {c.lineage.fixtureVersion}</dd></dl></details>
  </section>
  <section className="expression-chat" aria-label="Expression conversation" key={e.active}>
   <div aria-live="polite">{(f.conversation.length>3?f.conversation.slice(-2):f.conversation).map((m,i)=><article className={`chat-message ${m.role}`} key={`${f.revision}-${i}`}><span>{m.role==='user'?'You':'Fidelis'}</span><p>{m.text}</p></article>)}</div>
   {f.conversation.length>3&&<details><summary>Earlier expression conversation · {c.ticker}</summary>{f.conversation.slice(0,-2).map((m,i)=><p key={i}><b>{m.role==='user'?'You':'Fidelis'}:</b> {m.text}</p>)}</details>}
   <fieldset disabled={!!run.result}><form className="chat-composer" onSubmit={event=>{event.preventDefault();send()}}>
    <label className="sr-only" htmlFor="expression-thought">Expression preference for {c.ticker}</label>
    <textarea id="expression-thought" ref={composer} rows={2} value={f.draft} placeholder={a?'Refine your preference…':'What matters most in how you own this thesis?'} onChange={event=>dispatch({type:'EXPRESSION_DRAFT',ticker:e.active,text:event.target.value})} onCompositionStart={()=>{composing.current=true}} onCompositionEnd={()=>{composing.current=false}} onKeyDown={event=>{if(event.key!=='Enter'||event.shiftKey||composing.current||event.nativeEvent.isComposing||event.nativeEvent.keyCode===229)return;event.preventDefault();if(!event.repeat)event.currentTarget.form?.requestSubmit()}}/>
    <button type="submit" aria-label={`Send ${c.ticker} expression preference`} disabled={!f.draft.trim()}><svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M12 19V5m-6 6 6-6 6 6" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></button>
   </form></fieldset>
   <p className="wash-note">Local deterministic conversation · one response unlocks comparison. Your horizon is inherited; an explicit “horizon: … months/years” refines it for Expression only.</p>
  </section>
  {a&&inspected&&<>
   <section aria-label="Expression objective"><span className="overline">Your expression objective</span><h3>{intentNames[a.objective.intent]}</h3><fieldset disabled={!!run.result}><div className="expression-intents" role="group" aria-label="Correct demo interpretation">{expressionIntents.map(intent=><button key={intent} aria-pressed={a.objective.intent===intent} onClick={()=>dispatch({type:'EXPRESSION_INTENT',ticker:e.active,intent})}>{intentNames[intent]}</button>)}</div></fieldset><p className="wash-note">This is an editable demo interpretation, not an assessment of suitability or your financial circumstances.</p><dl className="expression-facts">{[['Horizon',`${a.objective.horizon} · ${a.objective.horizonSource}`],['Risk preference',a.objective.risk],['Timing tolerance',a.objective.timingTolerance],['Convexity preference',a.objective.convexity]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>Inherited path: {a.objective.path}</p></section>
   <section aria-label="Strategy-family comparison"><h3>Three ways to carry the same thesis</h3><p className="wash-note">Qualitative strategy families. No contract selection or expression score.</p><div className="strategy-families" role="group" aria-label="Inspect strategy families">{expressionFamilies.map(family=><button key={family} aria-label={`Inspect ${familyNames[family]}`} aria-pressed={f.inspected===family} onClick={()=>dispatch({type:'INSPECT_EXPRESSION_FAMILY',ticker:e.active,family})}><b>{familyNames[family]}</b><span>{family==='STOCK'?'No expiration · more capital':family==='LONG_CALL'?'Convex upside · premium and timing risk':'Lower net premium · capped upside'}</span><small>{family===a.preferred?'Preferred demonstration expression':family===a.alternative?'Alternative':'Available for comparison'}</small></button>)}</div><div className="strategy-reading" aria-live="polite"><h4>{familyNames[inspected.family]}</h4><dl className="expression-facts">{inspected.dimensions.map(d=><div key={d.label}><dt>{d.label}</dt><dd>{d.value}</dd></div>)}</dl><div className="expression-two-columns"><div><h4>Why it fits this research state</h4><ul>{inspected.fits.map(t=><li key={t}>{t}</li>)}</ul></div><div><h4>Why it may not</h4><ul>{inspected.constraints.map(t=><li key={t}>{t}</li>)}</ul></div></div></div></section>
   <section className="preferred-expression" aria-label="Preferred demonstration expression"><span className="overline">Preferred demonstration expression · {c.ticker}</span><h3>{familyNames[a.preferred]}</h3><p>{a.why}</p><h4>Tradeoff</h4><p>{a.tradeoff}</p><div className="expression-alternative"><h4>Alternative · {familyNames[a.alternative]}</h4><p>{a.alternativeWhy}</p></div><details><summary>What would change this expression?</summary><ul>{a.changes.map(t=><li key={t}>{t}</li>)}</ul></details></section>
   <section className="expression-two-columns" aria-label="Expression risks"><div><h3>Inherited from the thesis</h3><ul>{a.inheritedRisks.map(t=><li key={t}>{t}</li>)}</ul></div><div><h3>Created / amplified by the expression</h3><p className="wash-note">Inspecting {familyNames[f.inspected]}</p><ul>{inspected.risks.map(t=><li key={t}>{t}</li>)}</ul></div></section>
   <section aria-label="Expression success conditions"><h3>What must be true for this expression to work?</h3><p className="wash-note">{c.ticker} · {familyNames[f.inspected]} · conditions, not a probability of success</p><ol>{inspected.conditions.map(t=><li key={t}>{t}</li>)}</ol></section>
   <section className="expression-confirm" aria-label="Confirm demonstration expression"><span className="overline">Your choice · {c.ticker}</span><h3>{familyNames[f.inspected]}</h3><p>{f.inspected===a.preferred?'You are inspecting the preferred demonstration family.':'You are inspecting an alternative to the preferred demonstration family. Its constraints still apply.'}</p><button disabled={!!run.result} onClick={()=>dispatch({type:'CONFIRM_EXPRESSION',ticker:e.active})}>Use this expression for {c.ticker}</button>{f.confirmed&&<p role="status">Confirmed for {c.ticker}: {familyNames[f.confirmed]}</p>}<p className="wash-note">Inspecting another family does not change your confirmed choice. Changing the objective clears confirmation so you can review it again.</p></section>
  </>}
  {e.participants.filter(t=>e.finalists[t].analysis).length>1&&<section aria-label="Across your finalists"><h3>Across your finalists</h3>{e.participants.filter(t=>e.finalists[t].analysis).map(t=>{const row=e.finalists[t];return <button className="expression-cross-candidate" key={t} aria-label={`Compare ${t} expression`} onClick={()=>dispatch({type:'SWITCH_EXPRESSION_FINALIST',ticker:t})}><b>{t} · {familyNames[row.analysis!.preferred]}</b><span>{row.analysis!.why}</span><small>Tradeoff: {row.analysis!.tradeoff}</small><small>{row.confirmed?`Confirmed: ${familyNames[row.confirmed]}`:'Not yet confirmed'}</small></button>})}</section>}
  <aside className="expression-limitation" aria-label="Demonstration limitations"><p>{expressionLimitation}</p><p>Options can change how a thesis is expressed. They cannot repair a thesis that failed upstream.</p></aside>
  {!run.result&&<div className="discovery-proceed"><span>{e.participants.filter(t=>e.finalists[t].confirmed).length} of {e.participants.length} expressions confirmed</span><button disabled={e.status!=='COMPLETE'} onClick={()=>dispatch({type:'READY_FOR_RESULT'})}>Proceed to Result</button></div>}{run.result&&<p>Expression saved. Result preserves these confirmed decisions.</p>}
 </section>
}
