import type {ExpressionFamily,ExpressionIntent,ExpressionContext,ExpressionAnalysis,ExpressionObjective,ExpressionComparison} from './model';
export const familyNames:Record<ExpressionFamily,string>={STOCK:'Common Stock',LONG_CALL:'Long-Duration Call Exposure',CALL_SPREAD:'Call Debit Spread'};
export const intentNames:Record<ExpressionIntent,string>={UNSPECIFIED:'No strong preference',OWNERSHIP:'Direct ownership durability',CONVEXITY:'Asymmetric upside',DEFINED_RISK:'Defined-risk capital efficiency'};
export const expressionLimitation='Demonstration analysis · strategy families only. No live option chain is connected. No current strike, expiration, premium, bid/ask, implied volatility, Greek, liquidity, volume or open-interest data has been evaluated. This is not a live trade recommendation.';
interface FamilyFixture {capital:string;loss:string;upside:string;expiration:string;volatility:string;complexity:string;path:string;risks:string[];conditions:string[]}
// Public qualitative demonstration mechanics only; no live contracts, valuation or private synthesis.
const families:Record<ExpressionFamily,FamilyFixture>={
 STOCK:{capital:'Higher capital commitment than an option premium',loss:'Full invested capital can be lost; unlevered ownership',upside:'Uncapped participation',expiration:'None',volatility:'Price volatility remains; no option-premium sensitivity',complexity:'Direct ownership',path:'More tolerant of temporary price swings; permanent loss remains possible',risks:['Greater capital at risk than a premium-only exposure.','Full downside participation if the security deteriorates.'],conditions:['The economic thesis and acceptable upstream risk must persist.','Recognition and cash realization must justify the committed capital; absence of expiration does not ensure a return.']},
 LONG_CALL:{capital:'Premium-based; potentially more capital efficient',loss:'Entire premium can be lost',upside:'Convex, uncapped participation above contract economics',expiration:'Material; long duration still expires',volatility:'Material sensitivity to implied volatility and premium paid',complexity:'Option structure requires validated terms',path:'Sensitive to the path and time remaining, not just ultimate direction',risks:['Expiration can arrive before recognition.','The entire premium may be lost despite a directionally correct thesis.','Premium decay and changes in implied volatility can impair the expression.','Longer duration also allows competitive, macro and execution risks to develop.'],conditions:['Recognition must arrive within the eventual validated duration.','Realization must overcome the eventual premium and volatility burden; no quoted terms have been evaluated.']},
 CALL_SPREAD:{capital:'Lower net premium than a comparable outright call',loss:'Net debit at risk in the intended structure; implementation details matter',upside:'Capped participation',expiration:'Material; both legs expire',volatility:'Some premium/volatility burden may be reduced; sensitivity remains',complexity:'Two-leg structure; execution and assignment considerations',path:'Requires a realization path compatible with duration and capped upside',risks:['Expiration and loss of the net debit remain possible.','The upside cap can give up a large part of an unexpectedly strong thesis.','Multiple legs add execution and assignment complexity.'],conditions:['Recognition must develop within the eventual duration and be compatible with an upside cap.','Validated leg terms, execution and net premium must leave a defensible payoff; none have been priced here.']}
};
export function readDemoIntent(text:string):ExpressionIntent {
 // Conservative, transparent local shorthand. The user can correct it explicitly in the UI.
 if(/\b(no options|avoid options|avoid expiration|no expiration|direct ownership|common stock|stock-like|durability)\b/i.test(text))return 'OWNERSHIP';
 if(/\b(spread|cap(ped)? upside|defined[- ]risk|lower (cost|premium))\b/i.test(text))return 'DEFINED_RISK';
 if(/\b(asymmetric|convex(ity)?|long[- ]duration call|premium risk)\b/i.test(text))return 'CONVEXITY';
 return 'UNSPECIFIED';
}
export function openingQuestion(c:ExpressionContext):string {
 return `${c.ticker} survived adversarial review with ${c.t3.timing.state.toLowerCase()} timing. Your thesis horizon is ${c.horizon}. ${c.t3.timing.reason} For this expression, do you favor direct ownership durability, asymmetric upside, or defined-risk capital efficiency?`;
}
export function buildExpression(c:ExpressionContext,intent:ExpressionIntent,horizon=c.horizon):ExpressionAnalysis {
 const slow=['EARLY','UNCERTAIN','CATALYST-DEPENDENT'].includes(c.t3.timing.state);
 const burdenHigh=/high|demanding/i.test(c.t1.ve.state);
 const objective:ExpressionObjective={intent,horizon,horizonSource:horizon===c.horizon?'Inherited from thesis':'User refinement',risk:intent==='OWNERSHIP'?'Ownership downside; avoid option expiration':intent==='CONVEXITY'?'Premium risk preference — confirm it fits your intent':intent==='DEFINED_RISK'?'Net-debit limit with an upside cap':'Not specified; inspect the loss tradeoffs',convexity:intent==='CONVEXITY'?'Preferred':intent==='OWNERSHIP'?'Not prioritized':'Not required',timingTolerance:slow?'High tolerance needed; realization date unresolved':'Moderate tolerance needed; no exact catalyst date established',path:c.t3.timing.reason};
 const comparisons:ExpressionComparison[]=(['STOCK','LONG_CALL','CALL_SPREAD'] as ExpressionFamily[]).map(f=>{
  const x=families[f];
  const fit=f==='STOCK'?'Durable ownership of the surviving economics':f==='LONG_CALL'?(burdenHigh?'Constrained by embedded expectations':'Conditional convex exposure to surviving economics'):'Conditional exposure with deliberately capped upside';
  return {family:f,dimensions:[{label:'Thesis fit',value:fit},{label:'Horizon fit',value:f==='STOCK'?`No expiration; ${horizon} remains the research horizon`:`Requires validated duration appropriate to ${horizon}; availability unknown`},{label:'Timing tolerance',value:f==='STOCK'?'Higher; recognition can be delayed':slow?'Constrained by unresolved recognition timing':'Conditional on recognition before expiration'},{label:'Path tolerance',value:x.path},{label:'Capital intensity',value:x.capital},{label:'Loss character',value:x.loss},{label:'Upside participation',value:x.upside},{label:'Expiration sensitivity',value:x.expiration},{label:'Volatility sensitivity',value:x.volatility},{label:'Complexity',value:x.complexity}],
  fits:[`${c.ticker}: ${c.t3.survived}`,`Recognition: ${c.t1.recognition.state}; timing: ${c.t3.timing.state}.`,f==='STOCK'?'No expiration accommodates delays in the inherited realization path.':f==='LONG_CALL'?`A ${horizon} thesis makes duration a prerequisite to exploring convexity.`:'A willingness to trade some upside for lower premium can support a spread comparison.',`User objective: ${intentNames[intent]}.`],
  constraints:[c.t3.unresolved,`Expectations: ${c.t1.ve.state}. ${c.t3.pricedIn}`,f==='STOCK'?'Capital remains exposed to the entire stock decline.':f==='LONG_CALL'?'Longer duration is not less risk: time, volatility and thesis deterioration remain material.':'Capping upside is a deliberate compromise, not a universally safer expression.'],risks:x.risks,
  conditions:[`${c.ticker}: ${c.t3.survived}`,`The unresolved challenge must not become thesis failure: ${c.t3.unresolved}`,...x.conditions]};
 });
 const preferred:ExpressionFamily=intent==='OWNERSHIP'||(intent==='UNSPECIFIED')||slow||burdenHigh?'STOCK':intent==='DEFINED_RISK'?'CALL_SPREAD':'LONG_CALL';
 const alternative:ExpressionFamily=preferred==='STOCK'?(intent==='DEFINED_RISK'?'CALL_SPREAD':'LONG_CALL'): 'STOCK';
 const why=preferred==='STOCK'?`${c.ticker}'s ${c.t3.timing.state.toLowerCase()} timing and ${c.t1.recognition.state.toLowerCase()} recognition favor expiration-free durability in this demonstration. ${slow?'The inherited recognition clock takes precedence over a preference for leverage.':intent==='OWNERSHIP'?'This also matches your direct-ownership preference.':'Without a strong structure preference, stock provides the baseline comparison.'}`:preferred==='LONG_CALL'?`${c.ticker}'s surviving economics, ${c.t1.recognition.state.toLowerCase()} recognition and your asymmetric-upside preference make long-duration calls worth comparing. The ${horizon} horizon requires sufficient duration; it does not remove expiration risk.`:`${c.ticker}'s recognition is already progressing while expectations embed growth. Your defined-risk preference makes a debit spread credible if you accept an upside cap; the realization range is not a forecast.`;
 return {objective,comparisons,preferred,alternative,why,alternativeWhy:alternative==='STOCK'?'Common stock keeps the same thesis without option expiration or premium decay, at higher capital commitment.':alternative==='LONG_CALL'?'Long-duration calls provide a convex alternative if premium loss and recognition-before-expiration are acceptable; availability and terms require validation.':'A debit spread can reduce premium relative to a comparable call if capped upside is acceptable; unresolved timing can still defeat it.',tradeoff:families[preferred].risks.join(' '),changes:['More uncertain or later recognition strengthens the case for expiration-free ownership.','Earlier, more bounded realization could make a debit spread more compatible; no target range is inferred.','A higher expectations burden weakens the case for leveraged upside.','Deteriorating upstream evidence requires renewed research, not a different option structure.'],inheritedRisks:[...c.t2.fragilities.map(f=>`${f.mechanism}: ${f.effect}`),...c.t2.context.macro.map(m=>`${m.factor}: ${m.explanation}`),`Expectations burden: ${c.t1.ve.state}. ${c.t3.pricedIn}`,`Recognition / timing: ${c.t3.timing.reason}`,`Unresolved adversarial finding: ${c.t3.unresolved}`,`Evidence limitation: ${c.t3.integrity.limitation}`],limitation:expressionLimitation};
}
